### ISSUE TITLE
Add ZClip option

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#101]
Useful with shaders that should not be clipped by the came clipping planes, like skybox type shaders

**Comment by diogovtx** [comment]
True. This will take a bit of work, however, so I'll move it to v1.9.1.

**Comment by BOXOPHOBIC** [comment]
Additional info: https://docs.unity3d.com/Manual/SL-ZClip.html

**Comment by diogovtx** [comment]
Moved again to v1.9.2

**Comment by Dawie3565** [comment]
closed and moved to action. #223 as duplicated
