### ISSUE TITLE
Fix performance issues when switching between Shader Functions and Shaders

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#105]
> when switching from functions to shaders, and when doing it a few times, the switching is taking longer and longer
> but after saving the function a few times, maybe 10x, it can take up to a minute to switch back to the shader
> switching tabs
> happens in 2020.3+, was fine in 2019.4

**Comment by BOXOPHOBIC** [comment]
https://www.dropbox.com/t/OUlarQPqjlFzjzN2

1. Open Compute Motion Noise from TVE > Core > Functions
2. Open grass shader from TVE > Core > Shaders > Grass Subsurface Lit

3. Change noise function, save, switch to shader, repeat :smile:

For instance, I saved the function and it took 21 sec to go back to the shader
I modified the function again, after that it took 30 sec to go back to the shader

**Comment by diogovtx** [comment]
This was fixed by clearing Undo on Save/compile, also by adding option to disable Undo. System needs a complete rewrite. Already planned.
