### ISSUE TITLE
2D - New 2D Light Texture

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#113]
see LightTextureNode.cs

using Usage = UnityEditor.ShaderGraph.GraphDelta.GraphType.Usage;

namespace UnityEditor.ShaderGraph.Defs
{
    internal class LightTextureNode : IStandardNode
    {
        public static string Name => "LightTexture";
        public static int Version => 1;

        public static NodeDescriptor NodeDescriptor => new(
            Version,
            Name,
            functions: new FunctionDescriptor[] {
                new (
                    "LightTex0",
                    "Out = UnityBuildTexture2DStructNoScale(_ShapeLightTexture0);",
                    new ParameterDescriptor[]
                    {//TODO: need a light texture type, or a light tetexture REF
                        new ParameterDescriptor("Out", TYPE.Texture2D, Usage.Out)
                    }
                ),
                new (
                    "LightTex1",
                    "Out = UnityBuildTexture2DStructNoScale(_ShapeLightTexture1);",
                    new ParameterDescriptor[]
                    {
                        new ParameterDescriptor("Out", TYPE.Texture2D, Usage.Out)
                    }
                ),
                new (
                    "LightTex2",
                    "Out = UnityBuildTexture2DStructNoScale(_ShapeLightTexture2);",
                    new ParameterDescriptor[]
                    {
                        new ParameterDescriptor("Out", TYPE.Texture2D, Usage.Out)
                    }
                ),
                new (
                    "LightTex3",
                    "Out = UnityBuildTexture2DStructNoScale(_ShapeLightTexture3);",
                    new ParameterDescriptor[]
                    {
                        new ParameterDescriptor("Out", TYPE.Texture2D, Usage.Out)
                    }
                ),
            }
        );

        public static NodeUIDescriptor NodeUIDescriptor => new(
            Version,
            Name,
            displayName: "2D Light Texture",
            tooltip: "A 2D Light texture asset.",
            category: "Utility/Input/2D",
            synonyms: new string[0],
            hasPreview: false,
            selectableFunctions: new()
            {
                { "LightTex0", "LightTex0" },
                { "LightTex1", "LightTex1" },
                { "LightTex2", "LightTex2" },
                { "LightTex3", "LightTex3" }
        },
            functionSelectorLabel: "Blend Style",
            parameters: new ParameterUIDescriptor[] {
                new ParameterUIDescriptor(
                    name: "Out",
                    displayName: "Out",
                    tooltip: "selected 2D light texture"
                )
            }
        );
    }
}

**Comment by Dawie3565** [comment]
Bumping 2D workflow up from 1.9.2.0 to 1.9.1.1

**Comment by Dawie3565** [comment]
Bump for user requested

**Comment by Dawie3565** [comment]
for reference 


[[Render2DLightingPass.cs]](https://github.com/Unity-Technologies/Graphics/blob/b0544bef4aeca73b43985f0f71bcb15869e5c3d2/Packages/com.unity.render-pipelines.universal/Runtime/2D/Passes/Render2DLightingPass.cs#L18)

**Comment by Dawie3565** [comment]
for info from user 
https://blog.ldev.app/custom-2d-toon-lighting-in-unity-2021-2/

**Comment by Dawie3565** [comment]
Bump for more user requests

**Comment by diogovtx** [comment]
I have no idea what this is about. Please add a proper explanation about this on the original post description.

**Comment by Dawie3565** [comment]
@diogovtx 
unity docs are busted for this link 

its a new node needed for 2d Light texture 
![image](https://github.com/user-attachments/assets/b6c45b1b-4c96-47b6-8d50-ace7e88cb1b3)

**Comment by Dawie3565** [comment]
close and moved to Item #347 for tracking
