### ISSUE TITLE
Surface Gradient Bump Mapping Nodes

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#115]
see Unity link 
https://docs.unity3d.com/Packages/com.unity.surface-gradient-bump-mapping@0.1/manual/index.html

this will have a number of new nodes / shader functions to be added for ASE 
--- Surfgrad From Texture
--- Surfgrad Mixer
--- Surfgrad Resolve
--- Deriv From Height Texture
--- Deriv From Height Texture Grad
--- Deriv From Normal
--- Deriv From Normal Texture
--- Deriv From Normal Texture Grad
--- Surfgrad From Volume Gradient
--- Triplanar Weights
--- Generate Basis TB
--- Surfgrad From Normal
--- Surfgrad From Deriv
--- Surfgrad Scale Dependent From Deriv
--- Color Hex From Texture
--- Color Hex From Texture LOD
--- Surfgrad Hex From Texture
--- Planar Color
--- Planar Color LOD
--- Planar Surfgrad
--- Triplanar Color
--- Triplanar Color LOD
--- Triplanar Surfgrad

**Comment by diogovtx** [comment]
This should be SRP version agnostic.

**Comment by Dawie3565** [comment]
close and moved to Item #347 for tracking
