### ISSUE TITLE
Bug HDRP URP Precision setting 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#117]
-1- from main block in editor setting precision = Half does not affect /ase_main_pass/

-2- from main block in editor setting precision = Half close shader and re-open and compile actual code trips back to default “Float” even with-it showing set “Half” in editor main block options 

https://user-images.githubusercontent.com/47288655/197308255-04516a7d-2d90-446e-9247-c9ce79ed0a97.mp4

contact discord user **Alej** when fixed

**Comment by Dawie3565** [comment]
Note above issue is URP / HDRP 
however, user "inresin" is just reporting that custom templates in standard also have problem setting precision from main block also ... see discord

**Comment by diogovtx** [comment]
Fixed. Moved to 1.9.1 milestone, and closing.
