### ISSUE TITLE
Bug v1.9.1 preview 1 - Switch by Face broken in Surface Shader

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#119]
"removed some old VFACE code" - one guess is that surface shaders still use the old VFACE notation, the object is rendered always in green in the following example:

![image](https://user-images.githubusercontent.com/33637574/197406942-37914b55-2e99-46cc-b108-bcbd7f552c65.png)

**Comment by diogovtx** [comment]
Fixed. Moved to v1.9.1 and closing.
