### ISSUE TITLE
Node grid alignment

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#122]
Before - The node widths are not snapping to the grid, and header heights are different based on subtitles:
![image](https://user-images.githubusercontent.com/33637574/197463963-1cf7f417-6c55-4be1-873b-01dc37e72e41.png)

After - The node widths are snapping to a 16x16 grid, and header heights are the same:
![image](https://user-images.githubusercontent.com/33637574/197464482-cfa830bf-4ca9-480c-89d8-2d3a2c04712b.png)

*Package not provided due to public repo.

Notes by diogovtx:
- Make the node sizes aligned to grid cells?

**Comment by diogovtx** [comment]
I think this is a duplicate but definitely something that Dawie also requested, I'll move this to v1.9.2

**Comment by BOXOPHOBIC** [comment]
It was me the last time :D I just added it on git instead of google docs

**Comment by BOXOPHOBIC** [comment]
The changes to do it are minimal, I will provide them

**Comment by diogovtx** [comment]
Thank you!

**Comment by Dawie3565** [comment]
closing as completed
