### ISSUE TITLE
HDRP 12 Bug - undeclared identifier 'GetMaterialDebugColor'

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#123]
Repo: Enter a prefab and disable the lighting

Unity 2021.3.11
HDRP 12.1.7

![image](https://user-images.githubusercontent.com/33637574/197469708-4d123147-8b9f-49cd-bfbf-b5eafa1c0dca.png)

**Comment by Dawie3565** [comment]
ShaderPassForward.hlsl

`    bool viewMaterial = GetMaterialDebugColor(outColor, input, builtinData, posInput, surfaceData, bsdfData);

    if (!viewMaterial)
    {
        if (_DebugFullScreenMode == FULLSCREENDEBUGMODE_VALIDATE_DIFFUSE_COLOR || _DebugFullScreenMode == FULLSCREENDEBUGMODE_VALIDATE_SPECULAR_COLOR)
        {
            float3 result = float3(0.0, 0.0, 0.0);

            GetPBRValidatorDebug(surfaceData, result);

            outColor = float4(result, 1.0f);
        }
        else if (_DebugFullScreenMode == FULLSCREENDEBUGMODE_TRANSPARENCY_OVERDRAW)
        {
            float4 result = _DebugTransparencyOverdrawWeight * float4(TRANSPARENCY_OVERDRAW_COST, TRANSPARENCY_OVERDRAW_COST, TRANSPARENCY_OVERDRAW_COST, TRANSPARENCY_OVERDRAW_A);
            outColor = result;
        }
        else
#endif`

**Comment by diogovtx** [comment]
Fixed! closing
