### ISSUE TITLE
Update Amplify Shader Pack

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#128]
- Remove legacy SRP samples (<10.x)
- Remove substance samples
- Make HDRP samples version agnostic
- Make URP samples version agnostic

**Comment by Dawie3565** [comment]
1- move all functions into ASE for master index if selected 
2- remove all "Shader" samples from within ASE for only on variant into ASE Shader package 
3 - archive SRP api 10x 
4 - demo and sample updates for api 12x & 14x 

**set milestone for completion an compile with ASE v1.9.1.6**

**Comment by diogovtx** [comment]
Done in v2.0.0.
