### ISSUE TITLE
URP 10 shader keywords optimization

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#131]
#if ASE_SRP_VERSION < 110000
#pragma multi_compile _ _MAIN_LIGHT_SHADOWS
#pragma multi_compile _ _MAIN_LIGHT_SHADOWS_CASCADE
#else
#pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN			
#endif

----

#pragma multi_compile cannot be prefiltered and the above code will generate all keywords. This feature is only available in unity 2023.1 alpha

**Comment by Dawie3565** [comment]
Humm so we may need a template just for 11x ?

**Comment by BOXOPHOBIC** [comment]
> 

No, I think the new option with ase_srp_version > 110000 will be fine, didn check that feature in depth yet

**Comment by diogovtx** [comment]
no need, we just need to change this portion of code to use the new ase_srp_cond instead
I'm on it
