### ISSUE TITLE
Inconsistent ASE keywords

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#132]
A super small thing, all ASE keywords start with ASE_XXXFEATURE:
ASE_NEEDS_FRAG_WORLD_POSITION
ASE_NEEDS_FRAG_SHADOWCOORDS
ASE_FOG

_TRANSLUCENCY_ASE and _TRANSMISSION_ASE are different

**Comment by Dawie3565** [comment]
we have a plan in future to remove this from templates along with other things ?

**Tessellation** - remove from SRP templates and add a input port for tessellation. make tessellation node for SRP that reuses the Unity tessellation from Core 

**Translucency and transmission** could be removed from templates and built into a node or function? we already have the ports just need a node to reproduce this small chunk of code sounds easy

**Comment by BOXOPHOBIC** [comment]
**Translucency and transmission could be removed from templates and built into a node or function? we already have the ports just need a node to reproduce this small chunk of code sounds easy**

Would be even better, right now I use a custom GUI to assign my value to the ASE Translucency and transmission values

**Comment by Dawie3565** [comment]
it could be more optimized as we are repeating the code for Additional Lights plus this code is changing now in 14x so we could reduce the number of places we use it in for maintaining 

Note we don't need this in HDRP as we have thickness and diffusion profiles

the only part i have not replicate yet from this code is the for-transmission shadows 
you're welcome to use what i made below and build off it as needed 


**DESF Surface Input Thickness HDRP**
![image](https://user-images.githubusercontent.com/47288655/198906556-a28b09ac-7df8-4467-94d4-013455e58424.png)

**DESF Surface Input Thickness**
![image](https://user-images.githubusercontent.com/47288655/198906513-dc8769df-58d1-4e32-809d-f2e742011bc0.png)

[New Folder.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/9897031/New.Folder.zip)

**Comment by Dawie3565** [comment]
see zip file attached above

**Comment by diogovtx** [comment]
I think we can probably do that on next version => will keep this ticket open and move this to 1.9.2 milestone

**Comment by diogovtx** [comment]
Done and created a task to review transmission/translucency/tess
