### ISSUE TITLE
Fix cookie sampler derivatives warning introduced in URP 14x by Forward+

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#138]
> **gradient instruction used in a loop with varying iteration; partial derivatives may have undefined value**
> Compiling Subshader: 0, Pass: Universal Forward, Fragment program with _ADDITIONAL_LIGHT_SHADOWS _FORWARD_PLUS _LIGHT_COOKIES _MAIN_LIGHT_SHADOWS

Keep checking SG to see if/when this is fixed.
When finally fixed => update code Transmission, Translucency and SRP Additional Light accordingly.

**Comment by Dawie3565** [comment]
Reference
https://forum.unity.com/threads/unity-2022-2-0b13-urp-14-0-3-sg-shader-error-lightcookieinput-hlsl.1356428/

Unity Bug Reported in
CASE IN-21855

**Comment by Dawie3565** [comment]
close ASE action 
tracking in Unity Bug Reported in CASE IN-21855

**Comment by Dawie3565** [comment]
close ASE action tracking in Unity Bug Report CASE IN-21855
