### ISSUE TITLE
Fix depth prepass on PS4 (HDRP)

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#152]
> PS4 on 2021.3.13, TVE trees also have problems, they look transparent / overriden by the fog or skybox

https://discord.com/channels/562304069239177250/1045019320180277279

**Comment by BOXOPHOBIC** [comment]
More info: https://discord.com/channels/562304069239177250/1045019320180277279/1045719312620593272

**Comment by Dawie3565** [comment]
Closed – cannot replicate with latest ASE version 

Justification for Closing 

Testing conducted with
--- ASE v1.9.1.7
--- PS5 Devkit in 6.50 SDK
--- HDRP 14x 

We are not able to replicate any issues describe about motion vectors or flicking described in issue #153 & #152 

Testing included a full PS5 build/run with the latest TVE Engine component added in the scene including trees and bushes using TVE wind, and others behaviors featured by TVE do not show issues described in #153 & #152.
