### ISSUE TITLE
Fix motion vectors on XB1 and possibly PS4 (HDRP)

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#153]
> On Xbox One on 2021.3.13, TVE trees flickers like that.

https://discord.com/channels/562304069239177250/1045018035603378286

**Comment by Dawie3565** [comment]
06/28/2023 ASE v1.9.1.7 
testing in HDRP 14x PS5 Devkit in 6.50 SDK
**---- no issues found with motion vectors ----**

**Comment by Dawie3565** [comment]
Closed – cannot replicate with latest ASE version 

Justification for Closing 

Testing conducted with
--- ASE v1.9.1.7
--- PS5 Devkit in 6.50 SDK
--- HDRP 14x 

We are not able to replicate any issues describe about motion vectors or flicking described in issue #153 & #152 

Testing included a full PS5 build/run with the latest TVE Engine component added in the scene including trees and bushes using TVE wind, and others behaviors featured by TVE do not show issues described in #153 & #152.
