### ISSUE TITLE
Revamp Shader Function directives

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#158]
More control on how and when to add directives like #pragma.

Examples:
* SRP Additional Light adds lighting related keywords/multi-compile that are unnecessary outside Forward pass, adding unnecessary variants and compilation time
* Directives might change between SRP versions

Right now it's only possible to avoid both of these issues by using custom nodes instead of SFs. We need more flexibility in SFs to avoid having to write custom nodes, which is a lot more resource intensive.

**Comment by Dawie3565** [comment]
this action is
