### ISSUE TITLE
Update – Parallax Occlusion Mapping

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#163]
Move register inputs for Min/Max Samples to a Node Input 

we wish to add step optimization based on view angle to reduce the qty of steps when not needed.
however, the float value is only added in ase Parallax node thru a register.    

![image](https://user-images.githubusercontent.com/47288655/221369480-6c0122db-d0e3-4244-a828-fa570bc5f6d8.png)

we need an actual input in the node to feed the full result of function.
See SG Parallax Occlusion function for reference.  

![image](https://user-images.githubusercontent.com/47288655/221369619-f4a5f86a-c965-4213-a523-1ecb19d80b5e.png)

**Comment by Dawie3565** [comment]
to-do verify its working in SRP decals

**Comment by Dawie3565** [comment]
follow up for to-do decal 
use super sampling works incredibly well in Parallax and uses super sample index to reduce needed steps by 75% less steps 

may add action for myself to add super sampling function first in the amplify shader pack then follow up after for super sampling in Parallax as a decal sample with Parallax mapping function

**Comment by Dawie3565** [comment]
Notify user in discord SkyArcher when this item is progressed.

**Comment by Dawie3565** [comment]
@diogovtx for info also see other bug related to this item in #164 for Parallax Occlusion mapping issue in HDRP

**Comment by diogovtx** [comment]
Min/Max added as input to node in v1.9.3.1
