### ISSUE TITLE
Bug – Light color in BIRP main light cookie with deferred rendering  

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#166]
found in 2019.4.31 and 2019.4.40 BIRP 
reproduced on multiple systems. 

-- add unity ball and new shader with Light color node into debug port 
-- add a cookie texture on main light 

set camera render path: 
forward = works with cookie 
Deferred = returns light color black 

![image](https://user-images.githubusercontent.com/47288655/225363557-e77a25d7-d804-46c7-b54a-1ecc39cbdf74.png)

**Comment by diogovtx** [comment]
My result:
Deferred returns light color. White in my case.

We don't have lights in deferred pass. Should Light Color return black instead?

**Comment by diogovtx** [comment]
Light Color is not supported in deferred mode. Would showing this subtitle work?
![hM0HQSFlIz](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/ce60f7e3-01da-489a-a39b-b1810a68505a)

**Comment by diogovtx** [comment]
In BiRP, Light Color when connected to Emission or Debug, gets assigned to Emission which runs in ForwardBase pass (ambient/GI + emission). However, Light Color it only valid in ForwardAdd, but zeroed in ForwardBase. By logic, Emission shouldn't work but Debug should. No quick solution comes to mind, but I'll report back as soon as the situation changes.

**Comment by diogovtx** [comment]
No solution for this unfortunately. It's a Unity BiRP limitation where it won't give us the information we need on the ForwardBase/GBuffer passes. Unity BiRP has no notion of Main Light, so we have to wait until forwardAdd/Deferred passes to get light color information.
