### ISSUE TITLE
Impostors Pack – URP 12x Bake found with Empty Textures 

### ISSUE THREAD

**Issue by masscube** [AmplifyCreations/AmplifyShaderEditor-Feedback#180]
i have tested the asset (URP Shaders 12x) with variation of different prefabs in unity 2021.3. URP (12.1.10) and it always just creates an "empty" texture as you can see in the screenshots... i don't know why.

[Screenshot 1](https://drive.google.com/file/d/1wXX287kAL1ZNGFciBfCBImToxDuyOLaI/view?usp=share_link)
[Screenshot 2](https://drive.google.com/file/d/1P4k6d5VvRPlV_5aTPhllSBVvGZfQIn7A/view?usp=share_link)

I'm use the Amplify Impostors Version 0.9.8.3

**Comment by Dawie3565** [comment]
Closed in Amplify Impostors v0.9.8.4
