### ISSUE TITLE
Update – Color Node

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#182]
**Bug**

`Shader error in 'New Amplify Shader': Parse error: syntax error, unexpected $undefined, expecting TVAL_ID or TVAL_VARREF at line 7`

**Reproduce:**
--- Open any new shader
--- Paste RAW into shader and connect with input 
**http://paste.amplify.pt/view/raw/dfcf0b50** 

**found by discord user Creepy Pie 
comment**
"This happens because the "Color Mode" variable has the Enum attribute enabled, with Create Enums set, and one of the values has a negative number (-1).
Setting the number to 0 or higher solves the problem."

**Comment by diogovtx** [comment]
This is a Unity limitation. I'll force the enum values to positive numbers.

**Comment by diogovtx** [comment]
Fixed in v1.9.2.1
