### ISSUE TITLE
ASEStartScreen.cs UnityWebRequest

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#188]
please change behavior for ase start screen to not look for UnityWebRequest from 14x + higher 

Unity changed the default "Allow download over HTT* = not allowed 
unless user changes this to "Always allowed" A start window keeps popping warning errors in console

**Note Unity on restart keeps changing the default every time re-open Unity back to not allowed so its forever making inconvenience to users.** 

![image](https://user-images.githubusercontent.com/47288655/234939168-45c0496a-204a-4550-b161-4969a078c7b9.png)

**Comment by Dawie3565** [comment]
closed in v1.9.1.6

**Comment by LinqToException** [comment]
@Dawie3565: This is still occurring for me with 1.9.1.8 and Unity 2023.1 on every domain reload (with the option "On New Version" selected). Changing the changelog address from `http` to `https` as a workaround works for me.

From a standard point of view, is there a reason https isn't the default protocol used? All URLs that ASE uses seem to be utilizing http, which feels a bit dated.

**Comment by diogovtx** [comment]
Done. Thanks for the tip.

**Comment by Dawie3565** [comment]
Note 
Switched from http to https ASE v1.9.1.9
