### ISSUE TITLE
Impostor baking doesn't work on Apple Silicon (URP)

### ISSUE THREAD

**Issue by cemkoker** [AmplifyCreations/AmplifyShaderEditor-Feedback#189]
When I create a blank project (2021.3.24) install Amplify Impostors and try to bake the demo barrel. Unity crashes.

Already reported this a while ago (before xmas 2022) and here : 
https://forum.unity.com/threads/amplify-impostors-next-generation-billboards.539844/page-33#post-8765161 and sent you e-mail about it.

I'd appreciate taking into consideration since it's NOT usable on Mac yet.

**Comment by dev-fredericfox** [comment]
I have issues as well on 2022.2.19f1 with M1. It dosen't crash, but the baking just dosen't work and I keep getting the same error for every item I try to bake:
```
[AmplifyImpostors] Something went wrong with the baking process, please contact support@amplify.pt with this log message.
Value cannot be null.
Parameter name: shader  at (wrapper managed-to-native) UnityEngine.Material.CreateWithShader(UnityEngine.Material,UnityEngine.Shader)
  at UnityEngine.Material..ctor (UnityEngine.Shader shader) [0x00008] in /Users/bokken/build/output/unity/unity/Runtime/Export/Shaders/Material.bindings.cs:18 
  at AmplifyImpostors.AmplifyImpostor.RenderAllDeferredGroups (AmplifyImpostors.AmplifyImpostorAsset data) [0x00c4f] in /Users/ImpostersDemo/Assets/AmplifyImpostors/Plugins/Scripts/AmplifyImpostor.cs:1250 
  at AmplifyImpostors.AmplifyImpostorInspector.DelayedBake () [0x00000] in /Users/ImpostersDemo/Assets/AmplifyImpostors/Plugins/Editor/Inspector/AmplifyImpostorInspector.cs:960 
UnityEngine.Debug:LogWarning (object)
AmplifyImpostors.AmplifyImpostorInspector:DelayedBake () (at Assets/AmplifyImpostors/Plugins/Editor/Inspector/AmplifyImpostorInspector.cs:965)
UnityEditor.EditorApplication:Internal_CallDelayFunctions () (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:377)
```

**Comment by cemkoker** [comment]
I've been waiting for a fix for almost a year now; not even taking my request seriously. I'm done.

For anyone on Mac looking for a fix I'm happy with this one:
https://assetstore.unity.com/packages/tools/utilities/impostor-graph-251230

**Comment by dev-fredericfox** [comment]
Can you reopen the issue? They should still fix AmplifyShaderEditor, many of us have purchased it. Purchasing an other package is not a fix :D

**Comment by cemkoker** [comment]
Well ... I think there's a part between 'dreaming' and 'reality' - the sad reality is that they have more on their plate that they can handle (and it's always been the case) just a proof they're humans; for me I couldn't put my project on hold because of this. I'd be happy to try again when they fix it, somewhere around 2038 hopefully.

**Comment by dev-fredericfox** [comment]
You clearly missunderstand how issues work on github. It's fine I will make a new one, even if that is not supposed to work like that.

**Comment by cemkoker** [comment]
Yeah right I don't understand GitHub. Enjoy.
