### ISSUE TITLE
URP - MetaQuest / Stereo Multiview - Attached fixes for Quest / stereo rendering

### ISSUE THREAD

**Issue by chriscummings100** [AmplifyCreations/AmplifyShaderEditor-Feedback#195]
Hi there. I've fixed up stereo rendering on Oculus quest, so thought I'd provide our modified version here for you to peruse - better for us if the fixes go in anyway.

Aside from a couple of us-specific changes there are:
- fix for stereo multiview
- a change that you (I'm guessing) would want to make optional, switched to using alpha blending, as MSAA doesn't work well with alpha clipping and results in heavy aliasing, making it unusable for Quest/VR

Would be great if this goes in, as it'll mean we can reduce our own bespoke changes.
[amplify.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/11706576/amplify.zip)

**Comment by Dawie3565** [comment]
Moving to Amplify Impostors v0.9.8.5
need to verify closed in VR Quest

**Comment by Dawie3565** [comment]
Note @diogovtx 
i reviewed the files attached in zip and it looks like he was in URP12x

**Comment by Dawie3565** [comment]
@chriscummings100 
please clarify what is #define _MV_TONEMAP ?

**Comment by chriscummings100** [comment]
As I mentioned in the report, a few of the changes are specific to our code base which you'd need to strip out. _MV_TONEMAP is one of ours (forward tone mapping).

**Comment by Dawie3565** [comment]
> As I mentioned in the report, a few of the changes are specific to our code base which you'd need to strip out. _MV_TONEMAP is one of ours (forward tone mapping).

cheers ok that's what i suspected thanks

**Comment by diogovtx** [comment]
Added a AI_SKIP_ALPHA_CLIP compile time conditional for this purpose:
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/25316c26-f75c-4494-ba85-d18f7075219c)

Will try to add as many of the other changes as I can.

**Comment by diogovtx** [comment]
also added all the missing
`#pragma multi_compile _ UNITY_SINGLE_PASS_STEREO STEREO_INSTANCING_ON STEREO_MULTIVIEW_ON`
and
`UNITY_SETUP_STEREO_EYE_INDEX_POST_VERTEX(IN);`

everything else seemed too MV or VR specific

@chriscummings100 thanks for sharing these fixes

**Comment by Dawie3565** [comment]
Closed in Amplify Impostors v0.9.8.4
- Added AI_SKIP_ALPHA_CLIP to skip forced alpha test
- Fixed Quest/VR support across all URP versions
