### ISSUE TITLE
2D updates URP 15x

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#211]
Update templates and sprite nodes for changes in api 15x 

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/d2bd7980-df7b-4206-aca0-fe7df69a84db)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/07d42a7d-3482-4ea6-9bed-948419a9f5c2)

**Comment by Dawie3565** [comment]
Bumping 2D workflow up from 1.9.2.0 to 1.9.1.1

**Comment by Dawie3565** [comment]
Note notify user pHghost in discord when this is progressed.

**Comment by diogovtx** [comment]
Fixed in v1.9.3.1
