### ISSUE TITLE
Template Stencil Inline Properties hook losing connection. 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#212]
losing hook connections for stencil buffers when reopening shader 
verified in BIRP however also reported by user in URP 

repo BIRP 2019.4.31
--- open new shader 
--- connect hooks for StencilBuffer and save
http://paste.amplify.pt/view/raw/3c208fc5 
--- close shader editor 
--- reopen (see hooks have lost connection)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/db64e65d-ad57-4587-a7e3-18c5d8fd649a)

**Comment by liunliun** [comment]
zwrite and ztest also has this problem.

**Comment by Dawie3565** [comment]
URP 2d shaders now reporting same issue

**Comment by Dawie3565** [comment]
moved into millstone focused on user priorities to get completed.

**Comment by Dawie3565** [comment]
Note 

`hi david ,i found something new about this bug when reproducing, if you open the shader editor by double click the shader file,then the hooking will be losed,but if you open the shader editor from the reference image(first select a gameobject with meshrenderer,then click edit in inspector window),then the bug will not happen,everything will be ok. i think this is an important thing for the developer just in case they could not reproduce this issue.`


![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/33bbb2a3-7c74-4db2-b264-f35e8cfe1dc9)

**Comment by diogovtx** [comment]
Fixed in v1.9.2.3. I've attached the fix for anyone looking for a fix until we finish this version.

[ASE_DisconnectedInlinePropertyFix.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/13320986/ASE_DisconnectedInlinePropertyFix.zip)
