### ISSUE TITLE
Mac - URP 2021.3 12x & 2022.3 14x Decal shader 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#217]
Reported by NK Studio
test 2022.3 URP Decal shader in M2 Mac OS

User reports 
**2021.3 - shaders return magenta however no errors**
**2022.3 - shaders return magenta however no errors**

**2021.3** 12x
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/40a73e77-d39b-43c3-985e-0f35ab0a3e4d)

**2022.3** 14x
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/04e93588-a891-4762-b49d-b2a80f675828)

**Comment by diogovtx** [comment]
Can't replicate on URP 12x (2021.3.30). Looks fine on M1.
Is the user using the Universal/Decal template?
Is Decal feature enabled in the renderer?

**Comment by diogovtx** [comment]
Closed for now. Unable to replicate.

**Comment by diogovtx** [comment]
Was able to replicate in 14x+.
Fixed in v1.9.2.1
