### ISSUE TITLE
HDRP Unlit 14x Shadow Matte Error

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#218]
reported in 2022.3.6 and verified in 2022.3.7 (HDRP Unlit Template)

**error found when enable Shadow Matte on new shaders** 
`Shader error in 'New Amplify Shader': "Undefined area shadow filter algorithm" at /Github/DE v9.4.0 HDRP 14x/Library/PackageCache/com.unity.render-pipelines.high-definition@14.0.8/Runtime/Lighting/Shadow/HDShadowAlgorithms.hlsl(53)

Compiling Subshader: 0, Pass: Forward Unlit, Fragment program with SCREEN_SPACE_SHADOWS_OFF SHADOW_LOW
Platform defines: SHADER_API_DESKTOP UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS
Disabled keywords: DEBUG_DISPLAY INSTANCING_ON SCREEN_SPACE_SHADOWS_ON SHADER_API_GLES30 SHADOW_HIGH SHADOW_MEDIUM SHADOW_VERY_HIGH UNITY_ASTC_NORMALMAP_ENCODING UNITY_COLORSPACE_GAMMA UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_RGBM_ENCODING UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_VIRTUAL_TEXTURING _ALPHATEST_ON _SURFACE_TYPE_TRANSPARENT
`
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/e879516b-d5ac-4448-80d1-e66dd95b2d98)

**Comment by diogovtx** [comment]
Fixed in v1.9.2.1
