### ISSUE TITLE
Improve editor – Auto Snap to Grid Alignment

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#221]
Auto Snap to Grid Alignment

In ase version v1.9.1.6 we added improved grid snapping 
reference closed item #206  

this new action is to investigate adding a new option in the amplify preferences for auto snap to grid.

**Comment by diogovtx** [comment]
Done in v1.9.2

**Comment by Dawie3565** [comment]
closed in ASE 1.9.2.0
