### ISSUE TITLE
Add Vertex Tangent to Surface Shader

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#222]
Adding tangents requires custom expressions with surface shaders:
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/33637574/77c7e6f4-86ee-4ae7-a164-5c30f04254c4)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/33637574/3ac54ef6-b3f6-4b7b-bad0-b5a1f716427b)

**Comment by Dawie3565** [comment]
@BOXOPHOBIC 
please clarify is this action is a request for new terrain function.


terrain tangents will be provided for reference in the sample shader for terrain. 

see git item #20
https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/milestone/20

this update has a new terrain shader sample that covers BIRP, URP and new HDRP terrain.

**Comment by BOXOPHOBIC** [comment]
It is not necessarly related to terrain shaders, it can be anything where you need to set custom tangents. This will match the urp/hdrp templates which have the tangent port exposed already

**Comment by Dawie3565** [comment]
need to check as i think HDRP will be different than URP if i recall 

float3 tangent = cross(normal, positiveZ);
return float4(tangent, -1);

v.ase_tangent.xyz = cross ( v.ase_normal, float3( 0, 0, 1 ) );
v.ase_tangent.w = -1;

**Comment by Dawie3565** [comment]
this is same code as Unity "ConstructTerrainTangent"

**Comment by BOXOPHOBIC** [comment]
@Dawie3565 No need for any calculation of tangents, just to add a Local Vertex Tangent port to Surface Shaders.

**Comment by diogovtx** [comment]
Done in 1.9.2.2.
