### ISSUE TITLE
Mac OS - World Normal inside function bug 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#225]
**Error** 
unrecognized identifier 'appdata_full_custom'

BIRP - custom lighting template 
**The issue is on mac only and the build target is iOS**

-- world normal node inside shader function and plug into the custom lighting input 
-- compile on mac 

Note from user - The fix used before was to compile all shaders on PC and not compile any of the shaders on mac. If the PC compiles it then I load the same project on mac the shaders do not show an error unless recompile.

Function:
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/5f9a9be9-859b-4fb4-aaac-3dc1af073668)

Main Shader:
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/3aa751b7-cbfc-4f2f-9a05-3e52a60c6159)

Error:
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/5c88c544-ad54-420e-82ab-9a1db090142d)

**Comment by Dawie3565** [comment]
**Note for info only.**
user for above report was in Unity 2022.3.5 however he reports the bug on every unity version he used back to version 2021

**Comment by diogovtx** [comment]
Fixed in v1.9.2.1.
