### ISSUE TITLE
Light Color Node - HDRP invalid subscript "a"

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#227]
Light Color Node
in HDRP 12x the output "intensity" produces an error for invalid subscript "a" with _DirectionalLightDatas[0].color.a

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/e8318e8f-7b38-4608-972d-3917dcb42223)

**Comment by diogovtx** [comment]
Reopened due to bug in fix:
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/95add883-5e6f-428c-8fd9-34427a2a2fdd)

**Comment by diogovtx** [comment]
Fixed properly.
