### ISSUE TITLE
Dither node - pattern 4x4 bug 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#229]
dither node patter selection Int is stuck in 4x4 and will not change in its function header

note this issue is also observed in older ase versions from v189_035 and higher 
testing was conducted in v1.9.2.0 

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/7a9ffb15-909b-4f21-9eac-bb34a838d1d4)

**Comment by diogovtx** [comment]
Fixed in v1.9.2.1.
