### ISSUE TITLE
URP Unlit receive shadows. 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#233]
update templates URP 10x 12x 14x 15x 16x Unlit templates for receive shadow option.

**Comment by Dawie3565** [comment]
completed ase v1.9.3.4 

exposed new option for receive shadows 

URP Lit and Unlit templates 
10x 12x 14x 15x 16x 17x

**Comment by diogovtx** [comment]
Merged into v1.9.3.4
