### ISSUE TITLE
Improve Screen Position to be more intuitive

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#234]
Screen Position was historically based off Unity's own ComputeScreenPos(), which is poorly named. "Screen Position" meant Unity's NDC space, not screen space.

My proposal is to keep current functionality, to avoid breaking current shaders, but extend it to expose both normalized viewport UV and pixel position outputs directly, similar to UE's ScreenPosition node.
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/1f9d13cd-2bd6-4567-addb-d4d0136a3724)

**Comment by Dawie3565** [comment]
Note will need to update documentation also.

**Comment by Dawie3565** [comment]
for ComputeScreenPo see *Compute Screen Pos Node
https://wiki.amplify.pt/index.php?title=Unity_Products:Amplify_Shader_Editor/Compute_Screen_Pos

for Screen Position Node 
see action item #144

**Comment by diogovtx** [comment]
Going for #144 instead, to match ShaderGraph.
