### ISSUE TITLE
Bugs in 1.9.2.1 or general issues

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#235]
0. **URP/All Impostors:** I would rename all vertex/ase_normal/ase_tangent/clipPos to positionOS/normalOS/tangentOS/positionCS to unify all templates across pipelines (HDRP already uses this notation). This would help easier tracking of changes between ASE and Impostors and easier debugging (many things are names vertexXXX). This requires renaming them in the Impostors node as well

1. **URP 16:** Happens in the MotionVectors pass, URP 16, because clipPos is actually named positionCS

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/33637574/2a2b2889-207c-46da-ad08-52fd18b308fa)

2. **URP 14/16:** Something is wrong with the GBuffer pass in the Unlit template, URP 14, URP 16, ASE is not filling in anything

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/33637574/cf4fbec6-89e2-4ba2-b2de-56537c1037d5)

3. **URP:** ZWriteMode exists in both sub shader and Forward Pass. It should only exist in Forward and sync with the GBuffer pass / URP

4. **HDRP:** #pragma shader_feature_local _DOUBLESIDED_ON / #pragma shader_feature_local _ALPHATEST_ON should only be added if Double Sided and Alpha Clipping options are enabled. They are always set even if those features are not used!

5. Receive Decals/SSR are sort of inverted. A better namining would be Support Decals/SSR and add the disable keywords with it, and if support is disabled we should add #define _DISABLE_DECALS 1...

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/33637574/0593a491-5fdb-45d0-9b69-6c9a9bd43207)

**Comment by Dawie3565** [comment]
Item 5 for topic #define _DISABLE_DECALS will not be changed yet as this will affect multiple user and projects. 
all items must be verified to the common GUI for HDRP/URP as applicable. the decal shader features maybe better to become a constant and not option same as we did with shadows.

**Comment by Dawie3565** [comment]
Item **0** should be moved to impostor workflow for tracking. 
Items **1/2/4** are completed in ASE v1.9.2.2 
Item **3** needs more info to verify.

**Comment by BOXOPHOBIC** [comment]
Item 5, is all good with me (I use it with shader_feature_local anyways). If we keep the name Receive Decals, but only change the defines, nothing changes for the end user:
Receive Decals On = we add the shader_feature_local define, same as before
Receive Decals Off = we add the #define _DISABLE_DECALS 1 define so we actually turn off decals

**Comment by Dawie3565** [comment]
not really needed. 
shaders have _SupportDecals = 0 by default 
without adding shader_feature_local not present it is the same as = _DISABLE_DECALS
adding this _DISABLE_DECALS or removing this has no change in variants.  


GUI in HDRP looks like this 

            if (material.GetTag("RenderPipeline", false) == "HDRenderPipeline")
                if (material.HasProperty("_SupportDecals"))
                {
                    if (material.HasProperty("_SupportDecals"))
                    {
                        var control = material.GetInt("_SupportDecals");

                        bool toggle = false;

                        if (control > 0.5f)
                        {
                            toggle = true;
                        }

                        toggle = EditorGUILayout.Toggle("Receive Decals", toggle);

                        if (toggle)
                        {
                            material.SetInt("_SupportDecals", 1);
                            material.DisableKeyword("DECALS_OFF");
                        }
                        else
                        {
                            material.SetInt("_SupportDecals", 0);
                            material.EnableKeyword("DECALS_OFF");
                        }
                    }
                }

**Comment by Dawie3565** [comment]
Note 
even with _DISABLE_DECALS present even in Unity HDRP Lit shader a bug in unity still present in 16x and 17x even does not fully disable decals in emission layers. decals is heavy integrated into core systems it is not likely fully possible to remove it to give any benefit. 

based on this we should first ask why do we give option to turn it off with compile and instead just make it constant always with  shader_feature_local present
