### ISSUE TITLE
Update Light Attenuation Node

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#238]
--- update to add Multi Compiles for 15x and 16x 
--- update to optimize Multi Compiles to be added only in selected passes needed 

_see below for guidance:_ 

////////// URP10PragmaMultiCompiles
**"Forward" and "GBuffer"**
"multi_compile _ _MAIN_LIGHT_SHADOWS",
"multi_compile _ _MAIN_LIGHT_SHADOWS_CASCADE",
"multi_compile_fragment _ _SHADOWS_SOFT"

**"Forward"**
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",

////////// URP11PragmaMultiCompiles
**"Forward" and "GBuffer"**
"multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN",
"multi_compile_fragment _ _SHADOWS_SOFT"

**"Forward"**
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",

////////// URP12PragmaMultiCompiles
**"Forward" and "GBuffer"**
"multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN",
"multi_compile_fragment _ _SHADOWS_SOFT"

**"Forward"**
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",

////////// URP14PragmaMultiCompiles
**"Forward" and "GBuffer"**
"multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN",
"multi_compile_fragment _ _SHADOWS_SOFT",

**"Forward"**
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",
"multi_compile _ _FORWARD_PLUS"

////////// URP15PragmaMultiCompiles
**"Forward" and "GBuffer"**
"multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN",
"multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH",

**"Forward"**
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",
"multi_compile _ _FORWARD_PLUS"

////////// URP16PragmaMultiCompiles
**"Forward" and "GBuffer"**
"multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN",
"multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH",

**"Forward"**
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",
"multi_compile _ _FORWARD_PLUS"

**Comment by Dawie3565** [comment]
new update for URP 14x 

////////// URP14PragmaMultiCompiles
"Forward" and "GBuffer"
"multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE _MAIN_LIGHT_SHADOWS_SCREEN",

/*ase_srp_cond_begin:<140009*/
#pragma multi_compile_fragment _ _SHADOWS_SOFT
/*ase_srp_cond_end*/

/*ase_srp_cond_begin:>=140009*/
#pragma multi_compile_fragment _ _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH
/*ase_srp_cond_end*/

"Forward"
"multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS",
"multi_compile_fragment _ _ADDITIONAL_LIGHT_SHADOWS",
"multi_compile _ _FORWARD_PLUS"

**Comment by Dawie3565** [comment]
Moving back to highest priority 
Mobile is breaking without this change.

**Comment by Dawie3565** [comment]
////////////// new finding macOS 
macOS gives errors when used in api 14.0.10 (Unity 2022.3.18) 

Error:
undeclared identifier '_FOVEATED_RENDERING_NON_UNIFORM_RASTER' at /Users/tim/export/the_hunt/TheHuntGame/Library/PackageCache/com.unity.render-pipelines.universal@14.0.10/ShaderLibrary/Clustering.hlsl(30) (on metal)

**comments from Tim Conkling (Discord) verified traced to Light attenuation node**

We believe that the source of the issue is the Light Attenuation node
The script to generate this is in LightAttenuation.cs
In ASE Land:
Line 139 calls dataCollector.TemplateDataCollectorInstance.GetURPMainLight( UniqueId )
This in turn generates "Light ase_mainLight = GetMainLight( {0} );"
In Unity Shader Land:
There is a RealtimeLights.hlsl file, with the GetMainLight(...) definition
Am assuming that it's asking for shadow coords
If so, the MainLightRealtimeShadow(float4 shadowCoord) func is called in Shadows.hlsl
Two funcs are then potentially called via a branch (can't tell which branch)
SampleScreenSpaceShadowmap(shadowCoord)
Am wondering if this is the point of contention (probably test by disabling screen space shadows)
SampleShadowmap(...)
Doesn't seem to reference any foveated keywords
If not, then RealtimeLights.hlsl does all the setup for lighting
Line 38 calls ClusterInit(), which calls Line 25 in Clustering.hlsl
This is potentially where we hit the error on Macs

**Comment by tconkling** [comment]
Some additional context:

On macOS, running Unity 2022.3.19, URP 14, Amplify Shader Editor 1.9.3.2, and the Forward+ rendering pipeline, simply using the Light Attenuation node in a "URP/Unlit" shader causes a shader compilation error:

```
Shader error in 'MatcapGleam_URP': undeclared identifier '_FOVEATED_RENDERING_NON_UNIFORM_RASTER' at /Users/tim/export/the_hunt/TheHuntGame/Library/PackageCache/com.unity.render-pipelines.universal@14.0.10/ShaderLibrary/Clustering.hlsl(30) (on metal)
```

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/709022/beb06ff0-bc53-48cc-a4f3-86efbe084187)

We've fixed this locally by patching `URP/Unlit.shader` to #include the "FoveatedRenderingKeywords.hlsl" import in each `Pass` of the shader, just like URP/Decal and URP/Lit already do:

```
/*ase_srp_cond_begin:>=140010*/
#if ASE_SRP_VERSION >=140010
#include_with_pragmas "Packages/com.unity.render-pipelines.core/ShaderLibrary/FoveatedRenderingKeywords.hlsl"
#endif
/*ase_srp_cond_end*/

/*ase_srp_cond_begin:<140010*/
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/FoveatedRendering.hlsl"
/*ase_srp_cond_end*/
```

Patched Unlit template:
[Unlit.shader.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14316457/Unlit.shader.zip)

**Comment by diogovtx** [comment]
Fixed the macOS issue and the pragma update issue in v1.9.4. Many thanks to both of you!
