### ISSUE TITLE
Bug HDRP Unlit templates in Build. 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#247]
**Unlit templates 
HDRP 10x12x14x15x16x**

**error:** undeclared identifier '_BlendMode'

**to replicate:**
-- open new blank Unlit shader
-- compile with the latest released ase editor
-- select and press "Compile and show code"

actions:

**01 update for new syntax changes:** 
Renamed vertex to positionOS
Renamed ase_normal to normalOS
Renamed ase_tangent to tangentOS
Renamed clipPos to positionCS
Renamed worldPos to positions

**02 add new vertex tangent ports** 

**03 update for changes in each pass for Unlit debug display that seems to be the source for build errors.**

**Comment by Dawie3565** [comment]
please make this a priority as other bugs cannot fix util this completed first.

**Comment by Dawie3565** [comment]
items 01 and 2 are mostly completed. 

item 03 is pending review.

**Comment by diogovtx** [comment]
let's move "02 add new vertex tangent ports" to a new issue and push it to next update

**Comment by Dawie3565** [comment]
moved item 02 into new action #254 

closing this git action 
fixed error: undeclared identifier '_BlendMode' in ASE v1.9.3.0
