### ISSUE TITLE
Update function shadow mask

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#249]
update ase function "Shadow Mask"

Current code is per api 10x Lighting.hlsl

in 12x unity moved this to 12x GlobalIllumination.hlsl // Renamed -> LIGHTMAP_SHADOW_MIXING 

in 12x and higher the shadow mask code is now in RealtimeLights.hlsl
http://paste.amplify.pt/view/raw/11af76b2

To-do
careful review may be needed to check for adding new input for difference between static and dynamic lightmaps into shadow mask. 
Note Light map UV function may need update to have dynamic and static outputs rather than switch so they can be used together inline.  

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/ebf4a2fe-35a6-43b8-b13f-87564f3e09fc)

**Comment by diogovtx** [comment]
What exactly is this meant to fix?
