### ISSUE TITLE
URP 12x hybrid renderer V2 property breaks DOTS instancing

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#251]
user reported found in 2021.3.30
ENABLE_HYBRID_RENDERER_V2

**verify error reported** 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/362038c3-2901-43d6-a4f5-c42df0daae7c)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/a841e930-1e68-49f3-adf0-4789651fd9b4)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/87e4c9a5-2606-4b79-ae4b-63ade0bed5f8)

**Comment by Dawie3565** [comment]
contact discord user Evie for follow up

**Comment by EvieMae** [comment]
Was URP not HDRP using universalRP/unlit

**Comment by EvieMae** [comment]
Was fixed in newer version

**Comment by Dawie3565** [comment]
closing git action.
user updated to the latest amplify version (1.9.2.2) an verified fixed.
