### ISSUE TITLE
Remove URP Terrain Sample to save package space

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#252]
There's already a terrain sample on ASP, which is the big package.

**Comment by Dawie3565** [comment]
There are 4 functions in ASP for terrain samples + one sub function.

**BIRP / URP** 
--- Terrain 4 Layer
--- Terrain 4 Layer BasePass

**HDRP**
--- Terrain 8 Layer
--- Terrain 8 Layer BasePass

ASP has two terrain demos in all pipelines BIRP, HDRP and URP 
Terrain Simple
Terrain Snow

Note ASP functions for terrain also have one sub function called "Saturation" that is also only found in ASP.
 --- Saturation
 
 this Saturation function uses Grayscale using a dot product with the perceptual weights for the snow option.

**Comment by Dawie3565** [comment]
closed 
moved to ASP
