### ISSUE TITLE
Errors in templates when compiling all variants

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#253]
Some variants seem to be broken. We need to force-compile all variants and fix all the issues.
Affects both URP and HDRP. Examples below:

**URP/Unlit template:**
> ![Unity_REk47ov8r9](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/a95f4ea8-373a-423c-adc1-31633ac10de2)

**HDRP\Lit template**
> ![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/923d513b-d5a8-497c-95fd-cf014b70c37b)

**Comment by Dawie3565** [comment]
**URP Unlit** 

10x completed full build test with URP Unlit shader set with shader model 3.5 
could not reproduce. 

16x completed compile and show all variant test with unlit shader model 3.5 
could not reproduce. 

for URP please provide more info
