### ISSUE TITLE
Error Parallax Occlusion Node

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#255]
**found in BIRP 2019.3.31 and reproducer also in BIRP 2022.3.19**

- [ ] A) **--- error when use with height mapping into local vertex offset**
this error is for shader model however changing to higher shader model still will not fix it

- [x] B) **--- error for input anything other than int or float into sidewall step input**
when connect it auto forces disconnect of texture sample input
note in side shader function behavior is different
error will happen if try to use modified values for sidewall step
 such as reduce by viewing angle

**attached test file for reproducing.**
--- open in BIRP and find sticky notes

[Test.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14128855/Test.zip)

**Comment by Dawie3565** [comment]
Bumping for 1.9.3.4 balance overflow from 1.9.3.3

**Comment by diogovtx** [comment]
Fixed B, but A won't fix.

You can't use POM on vertex stage. Using the result of a POM on any node used to apply Local Vertex Offset will result in errors.
