### ISSUE TITLE
Update HD Emission Node 17x

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#256]
Update for change in HD Emission node  
HDRP 17x (first change found in 17.0.2 2023.3.0b5

multiplier = LightUtils.ConvertEvToLuminance(intensity);

change to 

multiplier = LightUnitUtils.Ev100ToNits(intensity);

**Comment by diogovtx** [comment]
This API does not seem to exist in the "com.unity.render-pipelines.core" package shader-code and is not referenced anywhere in the "com.unity.render-pipelines.high-definition" package shader-code.

The change you observed was made to script code, not shader code.
