### ISSUE TITLE
Update Dither Node DitheringNode.cs

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#266]
step operation in dither is returning artifacts due to interpolator imprecision.
one out of 16 fragments is 1, 16/16, which means it's doing input ≥ 1

suggestion change step into multiply 

dataCollector.AddLocalVariable( UniqueId, "dither" + OutputId+" = step( dither"+ OutputId + ", "+ driver + " );" );

change to 

dataCollector.AddLocalVariable( UniqueId, "dither" + OutputId+" = * ( dither"+ OutputId + ", "+ driver + " );" );

to replicate 
-- add dither node 
-- add vertex color and plug alpha into dither node
-- connect dither into main block alpha 
-- connect float 0-1 into main block alpha cutoff 
check results with a small value for alpha cutoff, expected results with vertex color =1 should be solid however results some fragments will disappear.

**Comment by Dawie3565** [comment]
Note contact user Nesterboy (discord) when action completed

**Comment by Dawie3565** [comment]
Note 
testing this in URP returns error for 
syntax error: unexpected token '*'

**Comment by Dawie3565** [comment]
closed in 1.9.3.3

**Comment by Dawie3565** [comment]
open bumped to 1.9.3.4 balance from 1.9.3.3

**Comment by diogovtx** [comment]
Also needs fixing when screenPos is negative.
