### ISSUE TITLE
Object Bounds Node

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#269]
Reder bounds are available in unity 2022.3 or higher
https://docs.unity3d.com/Packages/com.unity.shadergraph@14.0/manual/Object-Node.html

**Comment by BOXOPHOBIC** [comment]
Update: Renderer bounds can only be used in SRPs and if SG is imported.

**Comment by Dawie3565** [comment]
this is a duplicate Git item 
tracking in #110

**Comment by diogovtx** [comment]
Closing duplicate. Info moved to #110
