### ISSUE TITLE
Depth Fade Node URP

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#271]
Depth fade node returns error in **Unity 2022.3.21**

**Error:** redefinition of '_CameraDepthTexture_TexelSize'

Note 
in ASE depth fade node adds "#define REQUIRE_DEPTH_TEXTURE 1"

in Unity we trace this thru include ShaderGraphFunctions.hlsl

#if defined(REQUIRE_DEPTH_TEXTURE)
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"
#endif

**Change** 
Unity 2022.3.21 has change in DeclareDepthTexture.hlsl  resulting in redefinition error. 
float4 _CameraDepthTexture_TexelSize;

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/770c730a-0d95-4397-9ca1-051da2087ba2)

**Comment by Dawie3565** [comment]
**include also:** 
--- Depth Fade Node
--- Screen Depth Node

**Comment by Eniotnacram** [comment]
Is it easy to fix? So i can temporary fix it on my end?

**Comment by Loran007** [comment]
> Is it easy to fix? So i can temporary fix it on my end?

I temporarily removed all definitions of `_CameraDepthTexture_TexelSize`. ![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/53527943/df3005b2-86a8-44e8-a65e-45b42ec18c87)

**Comment by Dawie3565** [comment]
for internal info 

unity committed on Mar 9, 2023 
https://github.com/Unity-Technologies/Graphics/commit/98bd020f9c427721d7f20b260ca61f00b0789e98#diff-28fe67d85b81c34ed33761748c689d578224e5b7f9812eb115424f5f2a39870c

from brief review the change was made to support DynamicScalingClamping.hlsl

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/15d3ab9d-0134-4a64-b280-433ef0bec6ec)

**Comment by Eniotnacram** [comment]
I think i will wait for the fix aha, is it coming soon? 

Thank you :)

**Comment by kyleli** [comment]
> > Is it easy to fix? So i can temporary fix it on my end?
> 
> I temporarily removed all definitions of `_CameraDepthTexture_TexelSize`. ![image](https://private-user-images.githubusercontent.com/53527943/313954221-df3005b2-86a8-44e8-a65e-45b42ec18c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTA2MTYsIm5iZiI6MTcxMTQxMDMxNiwicGF0aCI6Ii81MzUyNzk0My8zMTM5NTQyMjEtZGYzMDA1YjItODZhOC00NGU4LWE2NWUtNDViNDJlYzE4Yzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIzNDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NmFkOGEwMGU5NGIxNTE4ODJlMzBkNzAwZTQwNDY2Y2EyOTg1MzM0OGU1MmNmYWRhZTYxMDM4OWVjNmQxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i9xcff3haDufAYItyEW65dNJhiledhuD-wZEWgITDmc)

Doing the same on my end for now. Would love to see an update.

**Comment by diogovtx** [comment]
Fixed in 1.9.3.3

**Comment by KrisDevelopment** [comment]
I am not seeing 1.9.3.3 in the package manager yet. Assume it's still going through Asset Store approval procedures?

**Comment by Dawie3565** [comment]
@KrisDevelopment 
yes, it may pop in into the asset store in morning as it had to go thru testing along with many other updates.  
they had one more merge to push today that just finished also

**Comment by Dawie3565** [comment]
for info only looks like unity will be fixing this so it does not happen again in future versions 2023.3
based on this we will need to keep a good look out for this issue to happen again in other unity versions not released yet

see 
https://github.com/Unity-Technologies/Graphics/pull/8051/commits/285f32445d96c67cf55ee9bb83856a5f9d5db2ab

**Comment by Dawie3565** [comment]
for info only 
unity PR UUM-66727 has reverted the change back in 2023.3.23
ASE v1.9.3.3 is fixed for all changes now and due for asset store release on or around 04/06/2024
