### ISSUE TITLE
AmplifyShaderEditor_v1.9.3.3_preview1 review comments 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#275]
this git action is for tracking internal review ASE v.1.9.3.3_preview_1

**Templates changes see attached file zip Templates ASE v.1.9.3.3_preview_1_2**
 --- updated HDRP templates 12x14x15x16x17x (depth offset logic)
 --- update URP unlit 12x14x15x16x17x fix Git item [#267](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/267) ( Dots)
 --- update URP 14x multiple templates fixed includes (new unity version conditional tags)
 
**See latest zip file in comments below**

**Comment by Dawie3565** [comment]
attached Zip 

**Templates changes see attached file zip Templates ASE v.1.9.3.3_preview_1_3**
--- updated HDRP templates 12x14x15x16x17x (depth offset logic)
--- update URP unlit 12x14x15x16x17x fix Git item #276 (Dots)
--- update URP 14x multiple templates fixed includes (new unity version conditional tags)
--- updated HDRP 17x for changes in Unity 6000_b11



[Templates ASE v.1.9.3.3_preview_1_3.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14610600/Templates.ASE.v.1.9.3.3_preview_1_3.zip)

**Comment by Dawie3565** [comment]
Update 

**Templates changes see attached file zip Templates ASE v.1.9.3.3_preview_1_4**
--- updated HDRP templates 12x14x15x16x17x (depth offset logic)
--- update URP unlit 12x14x15x16x17x fix Git item https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/276 (Dots)
--- update URP 14x multiple templates fixed includes (new unity version conditional tags)
--- updated HDRP 17x for changes in Unity 6000_b11
**--- HDRP set default for double sided = Enable** 

[Templates ASE v.1.9.3.3_preview_1_4.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14657642/Templates.ASE.v.1.9.3.3_preview_1_4.zip)

**Comment by Dawie3565** [comment]
**Templates changes see attached file zip Templates ASE v.1.9.3.3_preview_1_5**
--- updated HDRP templates 12x14x15x16x17x (depth offset logic)
--- update URP unlit 12x14x15x16x17x fix Git item https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/276 (Dots)
--- update URP 14x multiple templates fixed includes (new unity version conditional tags)
--- updated HDRP 17x for changes in **Unity 6000_b12**
--- HDRP set default for double sided = Enable
**--- Major updates HDRP Lit 10x12x14x15x1617x**
**--- Major updates HDRP Hair 10x12x14x15x1617x**

[Templates ASE v.1.9.3.3_preview_1_5.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14743667/Templates.ASE.v.1.9.3.3_preview_1_5.zip)

**Comment by Dawie3565** [comment]
**Templates changes see attached file zip Templates ASE v.1.9.3.3_preview_1_6**
--- updated HDRP templates 12x14x15x16x17x (depth offset logic)
--- update URP unlit 12x14x15x16x17x fix Git item 276 (Dots)
--- update URP 14x multiple templates fixed includes (new unity version conditional tags)
--- updated HDRP 17x for changes in Unity 6000_b12
--- HDRP set default for double sided = Enable
--- Major updates HDRP Lit 10x12x14x15x1617x
--- Major updates HDRP Hair 10x12x14x15x1617x

**since last update P1_5 fixed typo and some logic in hair templates** 

[Templates ASE v.1.9.3.3_preview_1_6.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14783813/Templates.ASE.v.1.9.3.3_preview_1_6.zip)

**Comment by Dawie3565** [comment]
**Templates changes see attached file zip Templates ASE v.1.9.3.3_preview_1_7**
--- updated HDRP templates 12x14x15x16x17x (depth offset logic)
--- update URP unlit 12x14x15x16x17x fix Git item 276 (Dots)
--- update URP 14x multiple templates fixed includes (new unity version conditional tags)
--- updated HDRP 17x for changes in **Unity 6000_b13**
--- HDRP set default for double sided = Enable
--- Major updates HDRP Lit 10x12x14x15x1617x
--- Major updates HDRP Hair 10x12x14x15x1617x


**since last update P1_6 fixed error in HDRP 10x lit for depth offset** 


[Templates ASE v.1.9.3.3_preview_1_7.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14813234/Templates.ASE.v.1.9.3.3_preview_1_7.zip)

**Comment by diogovtx** [comment]
1_7 changes now included

**Comment by Dawie3565** [comment]
for info recording changes from review Preview2 

Testing Preview2 has been completed:
--- 2019.3.31 (BIRP)
--- 2020.3.48 (10x URP/HDRP)
--- 2021.3.0 (12x URP/HDRP)
--- 2021.3.36 (12x URP/HDRP)
--- 2022.3.0 (14x URP/HDRP)
--- 2022.3.18 (14x URP/HDRP)
--- 2022.3.22 (14x URP/HDRP)
--- 2023.1.20 (15x URP/HDRP)
--- 2023.2.16 (16x URP/HDRP)
--- 6000.0.0b13 (17x URP/HDRP)

Sent in file "Templates ASE v.1.9.3.3_preview_2_1" 
Changes
--- updated HDRP Template Lit 14x (fix for decal error in api 14.0.8)
--- updated HDRP Template Hair 10x12x14x15x16x17x (fix small space correction in logic option)  
--- updated HDRP Template Decal 12x (fixed template error in api 12.1.0)
