### ISSUE TITLE
WebGL max Texture Size

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#281]
Investigate possible bug breaking ASE graph when used in WebGL platform and set override max texture size = 64 

![ASE BUG - MaxTextureSize](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/349327f1-7f71-4c24-a295-9a455d4e13c0)

**Comment by diogovtx** [comment]
Unfortunately I can't fix this, as far as I know. It's both a 1) Unity bug and a 2) usage issue.
1) Unity shouldn't apply this type of forced texture size limit on EditorUI/EditorResources; since they don't affect builds.
2) Textures should be resized on individual basis, not globally like this.

**Comment by Dawie3565** [comment]
Also, make sure textures have Max Size on WebGL platform these set properly when applicable

 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/fa18756a-e80c-422b-828a-f1d764b7bb40)
