### ISSUE TITLE
URP templates add Dots support in ExtraPrePass

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#286]
URP
investigate adding Dots support into Extra pre pass

**Comment by Dawie3565** [comment]
completed ASE v1.9.3.4

add dots in extra pre pass URP Lit and Unlit 
10x 12x 14x 15x 16x 17x

**Comment by diogovtx** [comment]
Merged into v1.9.3.4
