### ISSUE TITLE
AmplifyShaderEditor_v1.9.3.4 Review Comments

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#287]
Tracking and documenting changes for review:

**ASE_v1.9.3.4_Preview 0_1** 
--- URP Lit/Unlit fixed missing Dots support in ExtraPrePass (#286) 10x12x14x15x16x17x
--- URP Lit/Unlit exposed new option for Receive shadows (#233) 10x12x14x15x16x17x
--- URP Lit add new workflow type BlinnPhong 12x14x15x16x17x 

[ASE_v1.9.3.4_Preview 0_1.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14971244/ASE_v1.9.3.4_Preview.0_1.zip)

**Comment by Dawie3565** [comment]
**ASE_v1.9.3.4_Preview 0_2**
--- URP Lit/Unlit fixed missing Dots support in ExtraPrePass (#286) 10x12x14x15x16x17x
--- URP Lit/Unlit exposed new option for Receive shadows (#233) 10x12x14x15x16x17x
--- URP Lit add new workflow type BlinnPhong 12x14x15x16x17x

**--- URP Unlit fixed missing FoveatedRenderingKeywords.hlsl (#288) 14x16x17x
--- URP Lit fixed incorrect pragma for LOD Cross Fade in forward and Gbuffer pass 16x
--- URP Lit expose user option Enable SSAO (#289) 10x12x14x15x16x17x**

[ASE_v1.9.3.4_Preview 0_2.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/14981664/ASE_v1.9.3.4_Preview.0_2.zip)

**Comment by Dawie3565** [comment]
**ASE_v1.9.3.4_Preview 1_1**

Templates
---  **New light model option (PBR/Simple) URP Lit 12x & higher**
--- Fixed Lit/Unlit missing DOTS support in ExtraPrePass URP 10-17x (#286) 
---  Added Lit/Unlit option for "Receive shadows" URP 10-17x (#233) 
--- Fixed Unlit missing FoveatedRenderingKeywords.hlsl URP 14-17x (#288) 
--- Fixed Lit LOD Cross Fade pragma in Forward and Gbuffer passes URP 16x 
--- Added Lit/Unlit option for "Enable SSAO" URP 10-17x (#289) 
--- Fixed UI-Default template to avoid basic errors (e.g. removed _MainTex) 
--- **Fixed Lit/Fabric Decal error in 2023.1.0 HDRP 15x (#293)**

**Nodes** 
* Fixed "SRP Baked GI" and "Indirect Diffuse Light" nodes in HDRP 17x (#285)


[ASE_v1.9.3.4_Preview 1_1.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/15050292/ASE_v1.9.3.4_Preview.1_1.zip)

**Note P1_1 has changes in** 
--- HDRP 15x
--- URP 12x14x15x16x17x

**Comment by Dawie3565** [comment]
**ASE_v1.9.3.4_Preview 1_2**
--- New light model option (PBR/Simple) URP Lit 12x & higher
--- Fixed Lit/Unlit missing DOTS support in ExtraPrePass URP 10-17x (#286 )
--- Added Lit/Unlit option for "Receive shadows" URP 10-17x (#233 )
--- Fixed Unlit missing FoveatedRenderingKeywords.hlsl URP 14-17x (#288 )
--- Fixed Lit LOD Cross Fade pragma in Forward and Gbuffer passes URP 16x
--- Added Lit/Unlit option for "Enable SSAO" URP 10-17x (#289 )
--- Fixed UI-Default template to avoid basic errors (e.g. removed _MainTex)
--- Fixed Lit/Fabric Decal error in 2023.1.0 HDRP 15x (#293 )

**--- Fixed build error invalid subscript vmesh HDRP 10-17x (#295)**

**Note**
this update is for all HDRP templates.
HDRP 10x
HDRP 12x
HDRP 14x
HDRP 15x
HDRP 16x
HDRP 17x

attached 
[ASE_v1.9.3.4_Preview 1_2.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/15104208/ASE_v1.9.3.4_Preview.1_2.zip)

**Comment by Dawie3565** [comment]
**ASE_v1.9.3.4_Preview 1_3**
--- New lighting model option (PBR/Simple) URP Lit 12x & higher
--- Fixed Lit/Unlit missing DOTS support in ExtraPrePass URP 10-17x (286 )
--- Added Lit/Unlit option for "Receive shadows" URP 10-17x (233 )
--- Fixed Unlit missing FoveatedRenderingKeywords.hlsl URP 14-17x (288 )
--- Fixed Lit LOD Cross Fade pragma in Forward and Gbuffer passes URP 16x
--- Added Lit/Unlit option for "Enable SSAO" URP 10-17x (289 )
--- Fixed UI-Default template to avoid basic errors (e.g. removed _MainTex)
--- Fixed Lit/Fabric Decal error in 2023.1.0 HDRP 15x (293 )
--- Fixed build error invalid subscript vmesh HDRP 10-17x (295)

**Preview 1_3 changes** No new notes in change log needed (internal info only) 
adds comments from Cristian and final fix for new Lighting Model Simple
-- internal updated templates in URP 12x thru 17x 

**Attached Zip** 
[ASE_v1.9.3.4_Preview 1_3.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/15133830/ASE_v1.9.3.4_Preview.1_3.zip)

**Comment by diogovtx** [comment]
Merged all into 1.9.3.4 p2
