### ISSUE TITLE
URP Unlit templates 14x and Higher add missing FoveatedRenderingKeywords.hlsl

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#288]
URP unlit add FoveatedRenderingKeywords.hlsl 
This is added from unity 2022.3.16 and higher.

**Comment by Dawie3565** [comment]
Note: FoveatedRenderingKeywords.hlsl is not included in api 15x 

14x >=2022.3.16
15x (**not included**)
16x 17x included.

**Comment by diogovtx** [comment]
Merged into v1.9.3.4
