### ISSUE TITLE
URP Lit expose user option Enable SSAO 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#289]
URP Lit expose user option Enable SSAO 

SSAO is enabled by default always added in URP Lit 
this is an option for users to disable / remove. 

Option:Receive SSAO:false,true:true
true:SetDefine:Forward:pragma multi_compile_fragment _ _SCREEN_SPACE_OCCLUSION
false:RemoveDefine:Forward:pragma multi_compile_fragment _ _SCREEN_SPACE_OCCLUSION

Note for info only (Unlit) 
URP Unlit will come in future update via items (#242) (#196) 
for Unlit new pass Gbuffer is needed first for SSAO + updated syntax

**Comment by Dawie3565** [comment]
completed waiting review in ase v1.9.4

**Comment by diogovtx** [comment]
Merged into v1.9.3.4
