### ISSUE TITLE
Texture Parameter Node Error

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#294]
Error found in QA preview testing 1.9.3.4_P1

Testing 
--- BIRP 2019.3.4 

Error found when compiling shaders that used Texture Parameter Node
undeclared identifier '_StencilComp' at line xxxx

**Texture Parameter Node** has missing options:
--- Sprite Texture 
--- Tint
--- TextureSampleAdd 
--- MainTex_ST

![Capture](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/3cfa0409-dec3-4b8a-8a57-45be6267a0ae)

**Comment by Dawie3565** [comment]
HDRP 10x 2020.3.48

**amplify shader pack**
shader "UI Masked" using **Texture Parameter Node** will not open and breaks ASE 

**system crash**

**Comment by diogovtx** [comment]
Issue fixed in v1.9.3.4p2 by reverting UI-Default template changes made in p1.
