### ISSUE TITLE
ASE error AmplifyShaderEditor.OneMinusNode has no attribute (ASE v1.9.3.3) 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#296]
**User reported.** 
--- ASE 1.9.3.3.3 from asset store 
--- Unity 2022.3.21 URP 14.0.10 
--- new project fresh download 
--- Windows

QA could not fully reproduce, see below details  

User open ASE and nodes in graph breaking along with many errors in console 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/80522ccd-31eb-416f-bb92-046114dd0ec9)

after fix (see below) 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/ee4b3857-3cfb-4d12-9b60-e51b76d854cd)

// ParentNode.CommonInit ~line 404
The way the attribute was gotten for some of the nodes wasn't working, since the first attribute wasn't always that custom attribute (and it wasn't being given the custom attribute type in the getter)

////////////////////////////////////////
ParentNode.CommonInit ~line 404
////////////////////////////////////////

			System.Reflection.MemberInfo info = this.GetType();
			m_nodeAttribs = info.GetCustomAttributes( true )[ 0 ] as NodeAttributes;
			if( m_nodeAttribs != null )
			{
				m_content.text = m_nodeAttribs.Name;
				//m_content.tooltip = m_nodeAttribs.Description;
				m_tooltipText = m_nodeAttribs.Description;
				m_selected = false;
			}

change to 

			System.Reflection.MemberInfo info = this.GetType();

            var customAttributes = info.GetCustomAttributes(typeof(NodeAttributes), true);
            m_nodeAttribs = customAttributes.Length > 0 ? (NodeAttributes)customAttributes[0] : null;

			if( m_nodeAttribs != null )
			{
				m_content.text = m_nodeAttribs.Name;
				//m_content.tooltip = m_nodeAttribs.Description;
				m_tooltipText = m_nodeAttribs.Description;
				m_selected = false;
			}

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/21030557-502f-40d7-963a-fca99e1d8e78)

**Comment by Dawie3565** [comment]
[ParentNode.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/15080919/ParentNode.zip)

**Comment by Dawie3565** [comment]
completed review **see zip file in above comment** for changes 
tested in each api and change did not introduce any issues found

**Comment by Dawie3565** [comment]
---- improved editor stability (#296)

**Comment by Dawie3565** [comment]
Diogo can you please check MacOS to verify ok

**Comment by diogovtx** [comment]
This issue is OS agnostic. Fixed in 1.9.3.4p2. Different/cleaner code, but same fix.

**Comment by diogovtx** [comment]
User reported an oversight on this fix. Now properly fixed in 1.9.4.5.
