### ISSUE TITLE
SRP Baked GI Node Unity 14x 2022.3.26

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#297]
--- Unity **HDRP 2022.3.26** 

Unity change is specific to unity version in **14x cycle** >=2022.3.26 

Error 
: implicit truncation of vector type at line xxxx 

change is found in 
\Runtime\ShaderLibrary\**ShaderGraphFunctions.hlsl**

//////////////////////// **<2022.3.26** 
float3 shadergraph_HDBakedGI(float3 positionWS, float3 normalWS, float2 uvStaticLightmap, float2 uvDynamicLightmap, bool applyScaling)
{
#if defined(__BUILTINGIUTILITIES_HLSL__)
    bool needToIncludeAPV = true;
    return SampleBakedGI(positionWS, normalWS, uvStaticLightmap, uvDynamicLightmap, needToIncludeAPV);
#else
    return 0;
#endif
}

///////////////////////**>=2022.3.26** 

float3 shadergraph_HDBakedGI(float3 positionRWS, float3 normalWS, uint2 positionSS, float2 uvStaticLightmap, float2 uvDynamicLightmap, bool applyScaling)
{
#if defined(__BUILTINGIUTILITIES_HLSL__)
    bool needToIncludeAPV = true;
    return SampleBakedGI(positionRWS, normalWS, positionSS, uvStaticLightmap, uvDynamicLightmap, needToIncludeAPV);
#else
    return 0;
#endif
}

**Comment by Dawie3565** [comment]
detected change in ShaderGraphFunctions.hlsl
shadergraph_**LW**BakedGI
Note change from 2022.3.27 to 2022.3.28 

**<=2022.3.27**
float3 shadergraph_LWBakedGI(float3 positionWS, float3 normalWS, float2 uvStaticLightmap, float2 uvDynamicLightmap, bool applyScaling)


**>=2022.3.28**
float3 shadergraph_LWBakedGI(float3 positionWS, float3 normalWS, uint2 positionSS, float2 uvStaticLightmap, float2 uvDynamicLightmap, bool applyScaling)

**Comment by diogovtx** [comment]
Fixed in v1.9.4.
