### ISSUE TITLE
SRP Baked GI Node Unity 16x 2023.2.20

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#298]
--- Unity HDRP 2022.2.20

Unity change is specific to unity version in 16x cycle >=2023.2.20

Error
: implicit truncation of vector type at line xxxx

change is found in
\Runtime\ShaderLibrary*ShaderGraphFunctions.hlsl*

**Comment by diogovtx** [comment]
Was unable to replicate vector truncation, but was able to replicate the same error as #297.
Fixed in v1.9.4.
