### ISSUE TITLE
Template Fragment Data Node Bug

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#299]
--- tested in 2019.3.31 BIRP
--- ASE 1.9.3.4_P_1

**Nodes:
--- Template Fragment Data Node
--- Template Local Var Data Node 
--- Template Vertex Data Node**

**/////////////////// Template Fragment Data Node** 
does not show selections for Node Parameter

Node Parameter
**SubShader**
Select which subshader to get interpolated fragment data.
**Pass**
Select which Pass to get interpolated fragment data
**Data**
Select which interpolated fragment data to output

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/38e11f70-2395-42ec-9417-18d6357789f9)

**/////////////////// Template Local Var Data Node** 
same issue 

Node Parameter
**SubShader**
Select which subshader to get local var data
**Pass**
Select which Pass to get local var data.
**Data**
Select which local var data to output.
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/5a04567f-b44c-488d-8e1f-b86103c36076)

**/////////////////// Template Vertex Data Node**
same issue 

Node Parameter
**SubShader**
Select which subshader to get vertex data
**Pass**
Select which subshader to get vertex data
**Data**
Select which subshader to get vertex data
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/81fb7b97-0cdc-4665-a54e-1b2643a5b23b)

**Comment by diogovtx** [comment]
This only works with template shaders, not surface shaders. I will add a warning for when the usage conditions are not met.

**Comment by diogovtx** [comment]
How about this?
![M9TiKFgF8H](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/7001068/5cfe22a1-cf88-40f7-b42d-651d64a574eb)

**Comment by Dawie3565** [comment]
what i see is in BIRP 2019.4.31 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/f5b3a74f-ee04-464d-94d5-6f13cabe466c)

**Comment by Dawie3565** [comment]
no warning yet please push again ?

**Comment by Dawie3565** [comment]
Note still like to view the options when inside a shader function so not dependent on template

**Comment by Dawie3565** [comment]
checked in UI default ok 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/5fd653c3-9ac0-4d7a-bd07-969c7b89cdd2)

**Comment by Dawie3565** [comment]
legacy Lit ok 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/977c004b-d20e-4687-af45-0e845f9c5e31)

**Comment by diogovtx** [comment]
Fixed in v1.9.3.4 via Error display informing users that these nodes are not compatible with Surface shader type or Shader Function.
