### ISSUE TITLE
Update SRP Additional Light

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#3]
Node: "SRP Additional Light"
Transmission/Translucency Additional Vertex Light and Light Layers

See 
MainLightShadows = "_MAIN_LIGHT_SHADOWS";
MainLightShadowCascades = "_MAIN_LIGHT_SHADOWS_CASCADE";
CastingPunctualLightShadow = "_CASTING_PUNCTUAL_LIGHT_SHADOW";
AdditionalLightsVertex = "_ADDITIONAL_LIGHTS_VERTEX";
AdditionalLightsPixel = "_ADDITIONAL_LIGHTS";
AdditionalLightShadows = "_ADDITIONAL_LIGHT_SHADOWS";

Lighting.hlsl
See item Line 10
[[https://github.com/Unity-Technologies/Graphics/commit/a803690d88ec2a59f94092f43eebaf72138e8a](https://github.com/Unity-Technologies/Graphics/commit/a803690d88ec2a59f94092f43eebaf72138e8a1c)1c](https://github.com/Unity-Technologies/Graphics/commit/a803690d88ec2a59f94092f43eebaf72138e8a1c)

**Comment by Dawie3565** [comment]
Please reset priority into ase version 1..9.2 to be aligned with other milestones for 14x

**Comment by diogovtx** [comment]
Done

**Comment by diogovtx** [comment]
Done for 1.9.1. Closing this for now.
Let's create other tickets to add new features, if necessary.
