### ISSUE TITLE
ASE Instanced Terrain Option

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#300]
HDRP **Instanced Terrain** option is adding:
--- #pragma multi_compile_instancing
--- #pragma instancing_options assumeuniformscaling nomatrices nolightprobe nolightmap forwardadd

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/61ef4c43-81e3-4fe7-aa4e-e69ab6e43d18)

this behavior is different than BIRP and URP 
**it should not add pragma for instancing** 

/////////////////
Note it is also adding the incorrect one for terrain, use incorrect instancing can result is errors within some unity versions for LOD cross fade sharing the same constant buffers. 

#pragma instancing_options assumeuniformscaling nomatrices nolightprobe nolightmap forwardadd
**for terrain should be** 
#pragma  instancing_options assumeuniformscaling nomatrices nolightprobe nolightmap

//////////////  

**please make behavior same as BIRP and URP and do not add instancing pragma** 

Note 
within terrain we only add the below in defined passes 

instancing_options assumeuniformscaling nomatrices nolightprobe nolightmap
Forward, GBuffer

multi_compile_instancing
Forward,GBuffer,ShadowCaster,DepthOnly,DepthNormals

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/09c79773-dd36-46cc-8233-76c269730476)

**Comment by Dawie3565** [comment]
**more Updates requested by Cristain** 

**TerrainDrawInstancedHelper.cs**
---- BIRP Only ----

**Line 128**

/* 0 - tex coords*/"\t{0} = float4( (patchVertex.xy * uvscale.zw + uvoffset.zw), 0, 0 );\n",

change to 

/* 0 - tex coords*/"\t{0} = float4(sampleCoords, 0, 0 );\n",

**Comment by BOXOPHOBIC** [comment]
Fixed TerrainDrawInstancedHelper.cs instanced terrain code generation for BIRP Template Only 
[TerrainDrawInstancedHelper.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/15378461/TerrainDrawInstancedHelper.zip)

**Comment by diogovtx** [comment]
Thanks for the contribution @BOXOPHOBIC !

This is now fixed in v1.9.4 (previously v1.9.3.4)

**Comment by Dawie3565** [comment]
re open as not closed yet 

tested in HDRP 12x 2021.3.38 

when enable option for Instance terrain ase is still adding: 
#pragma multi_compile_instancing
#pragma instancing_options assumeuniformscaling nomatrices nolightprobe nolightmap forwardadd


this condition results is duplication and also ASE is adding the incorrect instancing option for terrain 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/2ddb1c30-a7df-4429-b5c4-c93128f532bb)

**Comment by diogovtx** [comment]
Fixed "forwardadd" being added to HDRP and URP. It's not used by Unity's URP/HDRP terrain shaders.

Everything else is pretty much a duplication problem, not specifically related only to "Instanced Terrain".
I've created a new issue to address these problems => #305 

Closing this issue.
