### ISSUE TITLE
SRP Premultiply shader Bug

### ISSUE THREAD

**Issue by AironT** [AmplifyCreations/AmplifyShaderEditor-Feedback#301]
Found a problem with Premultiply shaders after updating project to new version of Unity and new version of ASE. 
When I decided to recompile my old shaders I've notice pretty visible changes, their visuals changed.

I've check this on Unity/URP versions: 2022.3.5/14.0.8 and 2022.3.20/14.0.10
Also checked with versions of ASE: v1.9.1.5 and v1.9.3.2

So when I start digging I've found where things going wrong... 
In Forward pass there is define check with name "_ALPHAPREMULTIPLY_ON". If comment this, then shader works as should.
<img width="630" alt="devenv_YXx1TbeT5V" src="https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/6660183/a6da011f-6e54-45c2-b3e7-3ae8f68bd5dc">

After this I've cheked what logic was in legacy shaders and found this...
<img width="710" alt="devenv_m7W5aWm3gS" src="https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/6660183/e15ab3ec-d435-4e17-b75d-4689f4a902e0">

I think it's better to change the way it works by default to the same way as it was in old legacy shaders. Or add some sort of control to this feature in the graph.

---
### Additional info how I tested it.
I've created 3 shaders with the same logic inside: [Test_shaders.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/15188673/Test_shaders.zip)
1. ASE LegacyShader http://paste.amplify.pt/view/raw/61942a65
2. ASE URP Unlit (http://paste.amplify.pt/view/raw/b205e7a3)
3. ShaderGraph URP Unlit.

Inside you can see 2 parameters which called 'Emission' and 'Darkening'. Basically First myltiply on RGB channels and Second multiply on Alpha channel. 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/6660183/f2406ddc-408b-420f-aac9-06e995d311f5)
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/6660183/7a571822-33c9-45b5-a552-49d36d1d91cf)

In materials just set Darkening=0 and you will find that ASE URP Unlit works in different way then other 2 shaders, it become full transparent. 
<img width="162" alt="xnviewmp_Bukdk2TuR0" src="https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/6660183/7cc8f4ef-437f-4d9f-a209-5e19aba2f00b">

In erlier version it works the same, now it's not.

**Comment by AironT** [comment]
This also works fine and seems like more correct way.
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/6660183/7bc07c03-5d19-4701-a0a2-f57df85c9f06)

**Comment by diogovtx** [comment]
You are correct. The multiplication is already being done via Blend Mode (One, OneMinusSrcAlpha), so it's effectively accumulating two multiplications by alpha.

This has now been corrected and will be included in the v1.9.3.4 release.

Thank you for taking the time to write this very detail report. Highly appreciated.

**Comment by Dawie3565** [comment]
second user found issue also in default UI template 
bumped priority to highest critical
