### ISSUE TITLE
Square function aka Squared

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#309]
this function is set as vec4 input and users report returns odd results when use with float 

please make it to a official node with dynamic input 

also change name from Square to Squared

**Comment by Tiber-Legacy** [comment]
I'm personally not seeing any issues with this Function but I do think this would a good addition to ASE's default math nodes like how the One minus and Reciprocal Nodes are

**Comment by diogovtx** [comment]
>this function is set as vec4 input and users report returns odd results when use with float
I don't see a problem with this function either. You'll need to be more specific about what "odd results" actually mean.

>please make it to a official node with dynamic input
The input is configured with auto-cast and should correctly cast to float, float2 and float3.

Here's an example using float:
![B6tan7myJO](https://github.com/user-attachments/assets/d3ca97c9-7184-41fe-8d85-b0e3e5b9b40e)
And generating a correct output:
```
float temp_output_2_0_g1 = _Float0;
float3 temp_cast_0 = (( temp_output_2_0_g1 * temp_output_2_0_g1 )).xxx;
o.Albedo = temp_cast_0;
```

>also change name from Square to Squared
That wouldn't be in line with the rest of our functions: "Add" shouldn't be "Added".

**Comment by diogovtx** [comment]
>this function is set as vec4 input and users report returns odd results when use with float

I don't see a problem with this function either. You'll need to be more specific about what "odd results" actually mean.

>please make it to a official node with dynamic input

The input is configured with auto-cast and should correctly cast to float, float2 and float3.

Here's an example using float:
![B6tan7myJO](https://github.com/user-attachments/assets/d3ca97c9-7184-41fe-8d85-b0e3e5b9b40e)
And generating a correct output:
```
float temp_output_2_0_g1 = _Float0;
float3 temp_cast_0 = (( temp_output_2_0_g1 * temp_output_2_0_g1 )).xxx;
o.Albedo = temp_cast_0;
```

>also change name from Square to Squared

That wouldn't be in line with the rest of our function names: "Add" shouldn't be "Added".

**Comment by Dawie3565** [comment]
Squared is a math function 
Square is a shape 

conflict in names
