### ISSUE TITLE
URP Unlit breaking with Light Attenuation x Light Color

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#310]
Light Attenuation x Light Color

user reported: 
--- ase v1.9.4.4 
--- URP 2022.3.30 

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/31bbf977-d29f-466a-810a-11f52eeee473)

https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/353cd2bf-2e34-4f1d-9e9c-abdeb86d295a

**Comment by diogovtx** [comment]
Unfortunately, it's not possible to get Light Color working properly with URP/HDRP. It is a remnant of BiRP, which does 1 light per pass. Both URP and HDRP do multiple lights per pass.

Light Color, as is, only supports one Directional Light. That's it.

What I can do is add a warning informing the users of all this information.

**Comment by diogovtx** [comment]
Renamed both "Light Color" and "Light Attenuation" to "Main Light Color" and "Main Light Attenuation" respectively. This should make it more obvious what these nodes are for.
