### ISSUE TITLE
Updated templates 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#319]
URP 6000.0.9 has changes breaking ASE shaders 

**URP 17x 6000.0.9+**
add updated templates for URP 6000.0.9 and higher

**Comment by Dawie3565** [comment]
**Updated template**

**Comment by Dawie3565** [comment]
**Updated templates testing for item #320 Motion Vectors MoacOS** 
this item is still in testing waiting for user to verify 

[URP 17x 6000.0.9+.zip](https://github.com/user-attachments/files/16117539/URP.17x.6000.0.9%2B.zip)

**Comment by sacb0y** [comment]
There are also updates needed to the decal template.

![image](https://github.com/user-attachments/assets/747de2fa-9cc4-46b8-b5bf-518147d8fbb7)

**Comment by Dawie3565** [comment]
@sacb0y 
thank you this is a different issue now tracking in #321

**Comment by diogovtx** [comment]
Fixed in 1.9.6
