### ISSUE TITLE
URP 6000.0.9 MacOS error when includes ASE MotionVectors Pass

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#320]
Note 
could not be reproduced in SG by user 
-- testing SG graph with 'additional motion vectors' set to 'timebased' or 'custom' and no compile errors showing

ASE Error:
Shader error in 'New Amplify Shader': undeclared identifier 'RemapFoveatedRenderingResolve' at 6/Library/PackageCache/com.unity.render-pipelines.universal/ShaderLibrary/MotionVectorsCommon.hlsl(33) (on metal)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/f9f17521-e605-413a-b60c-8eb0efc7b2d7)

![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/128ab2c7-acd7-415b-9bf5-b3e15365e127)

**Comment by Dawie3565** [comment]
Note contact discord user "Greg" when progressed or need more info

**Comment by gregharding** [comment]
Basic details: macOS 13.6.7, Unity 6.0.9f1, Amplify Shader v1.9.5.1 (with template patch from https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/issues/319 applied). Project using URP with Forward+ rendering.

Most likely unrelated but in Unity 2023.2 the motion vectors option does not appear, but does appear (and is automatically enabled) in Unity 6 with the latest templates.

Also, when opening the shaders in Unity 6 it looks like any shader using tessellation is having the option automatically disabled for some reason (screenshot attached).

<img width="592" alt="tesselation_being_disabled" src="https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/150406/f6b2d91f-56f4-449d-b35f-ee44bf8731dd">

**Comment by Dawie3565** [comment]
@gregharding 
In Unity URP Motion Vector Pass is only added from 17x and higher 
this is enabled by default when open new shader same as Unity defaults 

about tessellation yes sorry that was expected as Tessellation is not compatible with Motion vectors and logic disabled it 
when you enable tessellation, it will also auto disable Motion vectors. 

 i will take a closer look at the logic again and see why unity had this enabled by default 
 
 thank you for point this out

**Comment by Dawie3565** [comment]
@gregharding 
Updated templates for testing MacOS in templates see item #319

**Comment by diogovtx** [comment]
Just tested this on Mac and it's also present in ShaderGraph. I found a ticket about it on Unity's Issue Tracker:
https://issuetracker.unity3d.com/issues/shader-error-in-shader-graphs-slash-screen-graph-undeclared-identifier-remapfoveatedrenderingresolve-when-trying-to-build-universal-3d-sample-project

Having said that, I was able to fix it on our end.
The fix will be included in ASE v1.9.6.
