### ISSUE TITLE
Indirect Diffuse Light Node - URP 6000.0.9 and higher Error

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#321]
Indirect Diffuse Light Node
testing 
--- ASE v1.9.5.1
--- Unity URP 6000.0.9 and 6000.0.10 
--- can be reproduced in ASE Lit and Unlit templates 

to reproduce open new shader and add Indirect Diffuse Light Node

Errors 
**OUTPUT_SH4': Too few arguments to a macro call.** 

![image](https://github.com/user-attachments/assets/8d41e59d-0f45-4114-a540-873bfd90eb5f)

![image](https://github.com/user-attachments/assets/588d51a0-20b5-48b9-9c18-97c7a54a4388)

**Comment by Dawie3565** [comment]
Note
from Unity 6000.0.9 and higher unity added changes related to USE_APV_PROBE_OCCLUSION

reference changes in Unity Lighting.hlsl

**Comment by diogovtx** [comment]
Fixed in 1.9.6
