### ISSUE TITLE
Ray Tracing Error HDRP 6000.0.11 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#323]
Project with ASE shader in scene reported as resulting in errors when Raytracing enabled 

--- HDRP 6000.0.11 

User reported how to reproduce: 
add any shaders made with ASE in scene and enable Screen Space Global Illumination tracing "Ray Tracing"

![image](https://github.com/user-attachments/assets/de3a78ab-cdcf-4efe-8f5e-b75a7c4216e5)

![image](https://github.com/user-attachments/assets/0c8d71f0-54b7-4c39-8e1d-b1729b5df4d4)

**Comment by JiRo20** [comment]
The issue happens each time you tick a Ray Tracing feature (RTGI, RTAO, RT Reflections...)
![image](https://github.com/user-attachments/assets/da9467b0-217e-47d1-80e2-90bdc2aee7cb)

And they do not work with any RT feature, for example objects with Amplify shaders do not catch RTGI, do not reflect, do not create Ambient Occlusion, for example here you see the difference between a typical Screen Space Reflection on the water:
![image](https://github.com/user-attachments/assets/9aaffd08-6b79-47e9-961a-42232f00e171)

And when I make it Ray Traced Reflections the models disappear from the reflection:
![image](https://github.com/user-attachments/assets/13fbc79c-cc31-41f9-8149-6d96c3a15eda)

Similarly, this is Screen Space Ambient Occlusion:
![image](https://github.com/user-attachments/assets/08940b60-7744-4967-8d92-de351ac20c5e)

When I make it RTAO the scene brightens up, which is not what AO does:
![image](https://github.com/user-attachments/assets/3150d131-2f38-408b-96b0-6a50f92ac559)

Similarly, RTGI is also broken in models using Amplify shaders, here I'm using the Performance preset (which is not working btw):
![image](https://github.com/user-attachments/assets/fece61ef-2d6e-4967-b748-36f88f44aa99)

And the Quality RTGI makes those shader completely black:
![image](https://github.com/user-attachments/assets/6be5468b-6749-4302-92c8-6474f8995255)

**Comment by JiRo20** [comment]
Also I need to mention, these errors only happen the first time you turn on an RT feature, if you clear console and turn off and turn back on those RT features the errors will not show up, but the RT features will remain broken in the scene regardless:
![image](https://github.com/user-attachments/assets/650baa41-fcf0-4b5d-9954-e773a4ec751f)

**Comment by diogovtx** [comment]
Please note that Raytracing is not yet supported by ASE.

**Comment by diogovtx** [comment]
I was unable to replicate these errors. Note that our templates do not have "RaytracingGBuffer" pass or any other Raytracing specific passes, so errors on them are not expected because they don't exist.

HDRP Raytracing support is planned for ASE 2.0
