### ISSUE TITLE
URP 6000.0.12 invalid subscript 'probeOcclusion'

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#326]
to replicate 
--- ASE v1.9.6.1 
--- Unity 6000.0.12 URP 3D 
--- Open ASP v2.3.0 (example "Animated Fire")

this error cannot be triggered until settings are setup and changed as follows:
--- install and set ASP settings 
![image](https://github.com/user-attachments/assets/00ee675f-566c-41a1-9f9b-336fd8fed83f)

with quality set "ASP Universal Render Pipeline Asset High Fidelity"
--- fine Lighting / "Light Probe System and set it = "Adaptive Probe Volumes"
![image](https://github.com/user-attachments/assets/3723cb86-092e-4b64-93cd-f6dcf9d4ec02)

Open Lighting settings and "Generate Lighting"
-- check errors related to 
![image](https://github.com/user-attachments/assets/71b9411b-3226-44ab-9433-21ef512124fa)

`                #if defined(DYNAMICLIGHTMAP_ON)
                inputData.bakedGI = SAMPLE_GI(inputData.staticLightmapUV, inputData.dynamicLightmapUV.xy, inputData.vertexSH, inputData.normalWS);
                #elif !defined(LIGHTMAP_ON) && (defined(PROBE_VOLUMES_L1) || defined(PROBE_VOLUMES_L2))
                inputData.bakedGI = SAMPLE_GI(inputData.vertexSH,GetAbsolutePositionWS(inputData.positionWS),
                    inputData.normalWS,
                    inputData.viewDirectionWS,
                    inputData.positionCS.xy,
                    inputData.probeOcclusion,
                    inputData.shadowMask);
                #else
                inputData.bakedGI = SAMPLE_GI(inputData.staticLightmapUV, inputData.vertexSH, inputData.normalWS);
                #endif`

**Comment by diogovtx** [comment]
Fixed in v1.9.6.2
