### ISSUE TITLE
FetchLightmapValue returns errors in BIRP 2020.3.48

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#327]
to reproduce open ASP in BIRP 2020.3.48
-- ASE v1.9.6.2
-- demo scene Unlit with Lightmap
-- open and compile shader "Unlit With Lightmap"
-- see Unity Console for below 2 errors: 

`GetLoadedImportedAssetsAndArtifactIDs called with invalid artifactID
UnityEditor.AssetImporter:SaveAndReimport ()
AmplifyShaderEditor.MasterNodeDataCollector:UpdateShaderImporter (UnityEngine.Shader&) (at Assets/AmplifyShaderEditor/Plugins/Editor/Nodes/Master/MasterNodeDataCollector.cs:1765)
AmplifyShaderEditor.MasterNode:UpdateShaderAsset (string&,string&,bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Nodes/Master/MasterNode.cs:672)
AmplifyShaderEditor.TemplateMultiPassMasterNode:Execute (string,bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Templates/TemplateMultiPassMasterNode.cs:2174)
AmplifyShaderEditor.MasterNode:Execute (UnityEngine.Shader) (at Assets/AmplifyShaderEditor/Plugins/Editor/Nodes/Master/MasterNode.cs:596)
AmplifyShaderEditor.ParentGraph:FireMasterNode (UnityEngine.Shader) (at Assets/AmplifyShaderEditor/Plugins/Editor/Graphs/ParentGraph.cs:2681)
AmplifyShaderEditor.AmplifyShaderEditorWindow:SaveToDisk (bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/AmplifyShaderEditorWindow.cs:1653)
AmplifyShaderEditor.AmplifyShaderEditorWindow:OnToolButtonPressed (AmplifyShaderEditor.ToolButtonType) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/AmplifyShaderEditorWindow.cs:1771)
AmplifyShaderEditor.ToolsWindow:OnButtonPressedEvent (AmplifyShaderEditor.ToolButtonType) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/Tools/ToolsWindow.cs:236)
AmplifyShaderEditor.ToolsMenuButton:Draw (single,single) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/Tools/ToolsMenuButton.cs:172)
AmplifyShaderEditor.ToolsWindow:Draw (UnityEngine.Rect,UnityEngine.Vector2,int,bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/Tools/ToolsWindow.cs:264)
AmplifyShaderEditor.AmplifyShaderEditorWindow:OnGUI () (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/AmplifyShaderEditorWindow.cs:5016)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

`Assertion failed on expression: 'it->second.IsValid()'
UnityEditor.AssetImporter:SaveAndReimport ()
AmplifyShaderEditor.MasterNodeDataCollector:UpdateShaderImporter (UnityEngine.Shader&) (at Assets/AmplifyShaderEditor/Plugins/Editor/Nodes/Master/MasterNodeDataCollector.cs:1765)
AmplifyShaderEditor.MasterNode:UpdateShaderAsset (string&,string&,bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Nodes/Master/MasterNode.cs:672)
AmplifyShaderEditor.TemplateMultiPassMasterNode:Execute (string,bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Templates/TemplateMultiPassMasterNode.cs:2174)
AmplifyShaderEditor.MasterNode:Execute (UnityEngine.Shader) (at Assets/AmplifyShaderEditor/Plugins/Editor/Nodes/Master/MasterNode.cs:596)
AmplifyShaderEditor.ParentGraph:FireMasterNode (UnityEngine.Shader) (at Assets/AmplifyShaderEditor/Plugins/Editor/Graphs/ParentGraph.cs:2681)
AmplifyShaderEditor.AmplifyShaderEditorWindow:SaveToDisk (bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/AmplifyShaderEditorWindow.cs:1653)
AmplifyShaderEditor.AmplifyShaderEditorWindow:OnToolButtonPressed (AmplifyShaderEditor.ToolButtonType) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/AmplifyShaderEditorWindow.cs:1771)
AmplifyShaderEditor.ToolsWindow:OnButtonPressedEvent (AmplifyShaderEditor.ToolButtonType) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/Tools/ToolsWindow.cs:236)
AmplifyShaderEditor.ToolsMenuButton:Draw (single,single) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/Tools/ToolsMenuButton.cs:172)
AmplifyShaderEditor.ToolsWindow:Draw (UnityEngine.Rect,UnityEngine.Vector2,int,bool) (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/Tools/ToolsWindow.cs:264)
AmplifyShaderEditor.AmplifyShaderEditorWindow:OnGUI () (at Assets/AmplifyShaderEditor/Plugins/Editor/Menu/AmplifyShaderEditorWindow.cs:5016)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

**Comment by diogovtx** [comment]
Unable to replicate on a later Unity version (2022.3.x).

Looks like a Library corruption issue. Definitely not an ASE issue.
