### ISSUE TITLE
Add more Object Data nodes

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#33]
* Object Position
* Object Bounds (only SRP 13.1+? [double check](https://docs.unity3d.com/Packages/com.unity.shadergraph@13.1/manual/Object-Node.html))
* Review Object Scale
* Move to new category Object or Object Data

**Comment by Dawie3565** [comment]
closing this item as its already tracking in item number 110

**Comment by Dawie3565** [comment]
closing this item as its already tracking in item number 110
