### ISSUE TITLE
Normal Reconstruct Z: Could make normalization optional

### ISSUE THREAD

**Issue by OwenTheProgrammer** [AmplifyCreations/AmplifyShaderEditor-Feedback#342]
![image](https://github.com/user-attachments/assets/e5aa074a-d989-4333-8ba8-a42b9f94bf0b)
![image](https://github.com/user-attachments/assets/2fb53615-cab1-4c4f-8c6c-5c127a005a39)

Because of the way this function is structured, we can guarantee the length of the resulting vector will be 1 unit in length, thus normalized. This will not be recognized by the compiler, meaning the normalization will not be optimized away automatically.

# Math Proof

```math
\begin{aligned}
\sqrt{x^2+y^2+z^2} &= 1\quad \text{Solve for } z \\
\left(\sqrt{x^2+y^2+z^2}\right)^{\textcolor{cyan}{2}} &= 1^{\textcolor{cyan}{2}} \quad \left(\sqrt{v}\right)^2 = |v| \\
|x^2+y^2+z^2| &= 1  \quad \{ \forall v \in \mathbb{R} \;|\; 0 \le v^2 \} \implies |v^2| = v^2\\
x^2 + y^2 + z^2 &= 1 \\
x^2+y^2+z^2 \textcolor{cyan}{- \left(x^2+y^2\right)} &= 1 \textcolor{cyan}{- \left(x^2+y^2\right)} \\
z^2 &= 1 - x^2 + y^2 \\
\textcolor{cyan}{\sqrt{z^2}} &= \sqrt{1 - x^2 + y^2} \quad \sqrt{z^2} = z \\
z &= \sqrt{1 - x^2 + y^2} = \textcolor{green}{\sqrt{1 - \left(x, y\right) \cdot \left(x, y\right)}}
\end{aligned}
```

# Shader Assembly Difference

| Current Node | Proposed New Node |
| :--------------: | :----------------------: |
| ![image](https://github.com/user-attachments/assets/82d101ea-75a4-4274-b7be-300588005735) | ![image](https://github.com/user-attachments/assets/e9ce7140-217a-4910-9d61-8393f15eaaff) |

This removes 3 shader instructions for free
- 5: dp3 or **d**ot **p**roduct of vector**3**'s
- 6: rsq or **r**everse **sq**uare root as in 1/sqrt(x)
- 7: mul which is just **mul**tiply

This will also put this node ahead of SG in terms of performance, as they also implement it the same way

**Comment by OwenTheProgrammer** [comment]
[Those nodes by request](http://paste.amplify.pt/view/raw/044e09a3)

**Comment by OwenTheProgrammer** [comment]
Ah, for safety of the xy components not being within the ranges and out of bounds like NaN values, I'll change the topic to request normalization as an option

**Comment by Dawie3565** [comment]
http://paste.amplify.pt/view/raw/ad521618
--- add function switch to make option 
--- set default as included for backward compatible 
--- added sticky notes 
![image](https://github.com/user-attachments/assets/ff67f719-4509-4d68-93c8-942a32f4afe8)

**Comment by diogovtx** [comment]
I agree the normalization should be optional. However, we need to keep in ON by default to ensure backwards compatibility.

Just a note about the proof: we can't ensure the inputs are normalized, and often they aren't (e.g. sampling normal maps), so normalization is sometimes necessary.

This is a very quick change, so I moved it up to v1.9.7.
