### ISSUE TITLE
Grab Screen Color: Floating point zero division warning

### ISSUE THREAD

**Issue by OwenTheProgrammer** [AmplifyCreations/AmplifyShaderEditor-Feedback#343]
![image](https://github.com/user-attachments/assets/cc90fe42-1a93-4a9a-b856-2c88c52ef14b)

http://paste.amplify.pt/view/raw/27bfe70b

Steps to recreate
- Add a Grab Screen Color node 
- Add texture coordinates node and feed it into the UV of the grab screen color node (This is not the intended use case)
- Enable "Normalize" for the Grab Screen Color node

Save and you'll get a warning.

![image](https://github.com/user-attachments/assets/841df890-f457-47b5-a2d3-8397486ba1b7)

This seems to be because the input gets converted with floating point zeros in the spaces float4(uv, 0.0, 0.0)/float4(uv, 0.0, 0.0);

**Comment by OwenTheProgrammer** [comment]
ASE version: 1.9.6.3 (most likely not the only version that does this)
Unity version: 2022.3.22
Unity Pipeline: Built-in (and probably the rest)
Template: verified behaviour with Unlit and Surface

**Comment by diogovtx** [comment]
This is a quick fix. Moved it up to v1.9.7

**Comment by diogovtx** [comment]
Decided not to fix this one. The expected input is a vec4, the onus of responsibility falls onto the user, to ensure the input is correct.
