### ISSUE TITLE
URP 12-17 Missing additionl light shadows with transmission/translucency

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#344]
GetAdditionalLight is missing a shadow mask input, the fix:

![image](https://github.com/user-attachments/assets/0d5cb46a-6feb-4aaf-9914-9e5ba12e4dd4)

**Comment by Dawie3565** [comment]
**Note for reference see** 
com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl

Light light = GetAdditionalLight(lightIndex, inputData, shadowMask, aoFactor);

**Comment by Dawie3565** [comment]
completed sent to Digo for include in ase v1.9.7 
updated URP Lit 10x12x14x15x16x17x
