### ISSUE TITLE
Implicit truncation of vector type warnings

### ISSUE THREAD

**Issue by LazyEti** [AmplifyCreations/AmplifyShaderEditor-Feedback#359]
Some nodes are generating Implicit truncation warning messages: 
![image](https://github.com/user-attachments/assets/ae1ad510-88b8-4a6f-8f9e-83e402b84445)

### Transform position:  "anything" to Screen:
`float3 worldToScreen279_g1368NDC = worldToScreen279_g1368/worldToScreen279_g1368.w;`
should become:
`float3 worldToScreen279_g1368NDC = worldToScreen279_g1368.xyz/worldToScreen279_g1368.w;`

### Grab Screen Color: 
`float4 fetchOpaqueVal2609 = float4( SHADERGRAPH_SAMPLE_SCENE_COLOR( ase_grabScreenPosNorm ), 1.0 );`
should become:
`float4 fetchOpaqueVal2609 = float4( SHADERGRAPH_SAMPLE_SCENE_COLOR( ase_grabScreenPosNorm.xy ), 1.0 );`

i think there might be more cases where this happens like **transform direction View to Clip** but I didn't bother writing them down when they appeared so more testing is probably in order to catch them all.
the warnings are harmless but its just in the way

**Comment by Dawie3565** [comment]
@LazyEti 
hello, thank you for the report 
to replicate we will need a bit more info including 
--- verify ASE version 
--- Verify Unity version 
--- Verify Unity Pipeline 
--- Verify what ASE templates used in ways to reproduce

**Comment by LazyEti** [comment]
@Dawie3565 
ASE: 1.9.7.1 (latest)
Unity: 2022.3.19f1
Pipeline: URP
Template: Universal/(any)

**Comment by Dawie3565** [comment]
**added to 1.9.7.2 milestone** 

verified errors in:
--- api 10.10.1 URP 2020.3.48 
--- api 14.0.10 URP 2022.3.19 
--- api 14.0.11 URP 2022.3.53
--- api 17.0.3 URP 6000.0.28

http://paste.amplify.pt/view/raw/222adb37
![image](https://github.com/user-attachments/assets/fbc0e668-90df-47b5-808e-f337198e40cf)

**Comment by Dawie3565** [comment]
@diogovtx 

for HDRP possible related or new Git ?
same test but this returns breaking errors 
--- api 14.0.11 **HDRP** 2022.3.53

![image](https://github.com/user-attachments/assets/c2ea4f8c-c02b-483d-959a-2e8213c5897b)
