### ISSUE TITLE
Main Light Color Node

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#367]
Add Main Light Color Node in lit/Unlit shader and turn off the main light in scene 
--- results in blowing out 

reproduced in 2020.3.48 (10x)
reproduced in 2021.3.45 (12x)
reproduced in 2022.3.53 (14x)
reproduced in 6000.0.29 (17x)

![image](https://github.com/user-attachments/assets/ce4cf2bf-5d6f-457b-999b-44265ee2855d)

**Comment by diogovtx** [comment]
URP or HDRP?
Forward or Deferred?

**Comment by Dawie3565** [comment]
URP 

Note 
this node is not supported in HDRP

**Comment by diogovtx** [comment]
Tracked it down to a division by zero. No lights, no intensity. Fixed.
