### ISSUE TITLE
Fix viewDir node bug in HDRP Decal Projector

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#50]

**Comment by diogovtx** [comment]
Notes
- Tangent-space viewDir node is broken
- Any tangent related nodes are bound to be broken ( decal tangent and bitangent are constant )

**Comment by Dawie3565** [comment]
add check for sprite renderer URP 12x 
reported issues by user in discord "Object to WorldPosition"
