### ISSUE TITLE
2D - Review and fix URP sprite/2D shaders

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#53]
add check for sprite renderer URP 12x
reported issues by user in discord "Object to WorldPosition"

**Comment by Dawie3565** [comment]
Bumping 2D workflow up from 1.9.2.0 to 1.9.1.1

**Comment by Dawie3565** [comment]
All URP 2D templets are updated in ase v1.9.7 

need more info about details for this subject issue 
please open new ticket as this action was 2 years old
