### ISSUE TITLE
Bug - Unity 2022 amplify RAW copy paste

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#6]
RAW copy paste does not work in 2022

**Comment by diogovtx** [comment]
Seems to be a network permissions bug in Unity beta.

**Comment by Dawie3565** [comment]
**Closed** 
Unity should be set "Allow downloads over HTTP" within window player settings 
**Project Settings/Player/Configuration** 
![image](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/assets/47288655/fe658379-071f-4bb6-8a71-a4dd4ed4e763)

**reference** 
https://docs.unity.cn/2022.2/Documentation/Manual/playersettings-windows.html
