### ISSUE TITLE
New –  Saturation

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#64]
SaturationNode.cs

[SaturationNode.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/9711506/SaturationNode.zip)

note i think ase can make two nodes 
-- Saturation
-- Saturation HSV

see DESF functions for reference

**Comment by Dawie3565** [comment]
Marked as completed waiting review. 
see 
DESF Color Saturation

**Comment by Dawie3565** [comment]
Closed
included in ASE shader pack

**Comment by diogovtx** [comment]
Added to ASE.
