### ISSUE TITLE
New – Exposure

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#72]
note this is HDRP 
https://docs.unity3d.com/Packages/com.unity.shadergraph@13.1/manual/Exposure-Node.html

[Exposure-Node.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/9711620/Exposure-Node.zip)

**Comment by diogovtx** [comment]
Added in 1.9.6.2
