### ISSUE TITLE
New – Multiple Logic Type Nodes 

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#74]
- [x] **All** -> Completed, added in ASE v1.9.1.6)
AllNode.cs
https://developer.download.nvidia.com/cg/all.html 

- [x] **Any** -> Completed, added in ASE v1.9.1.6
AnyNode.cs
https://developer.download.nvidia.com/cg/any.html

- [x] **Branch** -> Duplicate, can be emulated using ASE **Compare** node
BranchNode.cs  ((don't replay me with Use Lerp!!!)) thank you sir 

- [x] **Comparison** -> Duplicate, can be emulated using ASE **Compare** node
ComparisonNode.cs

- [x] **Is Infinite** -> Completed, added in ASE v1.9.3.4
IsInfiniteNode.cs
https://developer.download.nvidia.com/cg/isfinite.html

- [x] **Is NaN** -> Completed, added in ASE v1.9.3.4
IsNanNode.cs

- [x] **Nand** -> Completed, added in ASE v1.9.3.4
NandNode.cs

- [x] **Not** -> Completed, added in ASE v1.9.3.4
NotNode.cs

- [x] **Flip** -> WIP, to be added in ASE v1.9.3.4
FlipNode.cs

**Comment by Dawie3565** [comment]
2 items completed see ( Any ) ( Branch )
DESF Logic Any
DESF Logic Branch

will hold for review when other are ready

**Comment by Dawie3565** [comment]
-- All **(completed added in ASE v1.9.1.6)**
-- Any **(completed added in ASE v1.9.1.6)**
-- Branch
-- Branch on Input Connection
-- Comparsion
-- Is Infinite
-- Is NaN
-- Nand
-- Not
-- Flip

**Comment by diogovtx** [comment]
"Is Infinite" and "Is NaN" now implemented in v1.9.3.4

**Comment by Dawie3565** [comment]
-- All (completed added in ASE v1.9.1.6)
-- Any (completed added in ASE v1.9.1.6)
-- Branch
-- Branch on Input Connection
-- Comparsion
-- Is Infinite (completed added in ASE v1.9.3.4)
-- Is NaN (completed added in ASE v1.9.3.4)
-- Nand
-- Not
-- Flip

**Comment by diogovtx** [comment]
"Not" and "Nand" now implemented in v1.9.3.4

**Comment by diogovtx** [comment]
"Flip" now implemented in v1.9.3.4
