### ISSUE TITLE
New – Reciprocal

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#77]
ReciprocalNode.cs

also see DESF Math Reciprocal

[ReciprocalNode.zip](https://github.com/AmplifyCreations/AmplifyShaderEditor-Feedback/files/9711697/ReciprocalNode.zip)

**Comment by diogovtx** [comment]
Also add "Switch By Shader Target" node for this and other cases:
>= 5.0 use rcp( x )
< 5.0 use 1/x

**Comment by Dawie3565** [comment]
please make By into by with lowercase letter 
 Switch by Shader Target

**Comment by Dawie3565** [comment]
closed added in ase v1.9.1.6
