### ISSUE TITLE
Change minimum version to 2019.4.31f1 LTS

### ISSUE THREAD

**Issue by diogovtx** [AmplifyCreations/AmplifyShaderEditor-Feedback#88]
This is to support VRChat. Double check VRChat's current version first.

**Comment by Dawie3565** [comment]
https://docs.vrchat.com/docs/current-unity-version

**Comment by Dawie3565** [comment]
Note 
soon as this VRChat changes i will push the min version up into higher version something 202x .. wait and see when it happens and what is current at that time

**Comment by Dawie3565** [comment]
Note if they take tooo long aka early next year i will ump 2019 regardless of VRchat or not

**Comment by diogovtx** [comment]
Current plan is minimum 2020 as soon as VRChat upgrades. Right now 2019.4.31, instead of 2019.4.40 is low effort, so doable.
