### ISSUE TITLE
Nodes & Functions New Node – TwoSidedSign

### ISSUE THREAD

**Issue by Dawie3565** [AmplifyCreations/AmplifyShaderEditor-Feedback#99]
add new useful node for TwoSidedSign
category = Math Round

http://paste.amplify.pt/view/raw/b1edbf39

![image](https://user-images.githubusercontent.com/47288655/196000409-d8741b4c-8939-4842-a7b1-4eb46ad584ad.png)

**Comment by diogovtx** [comment]
There were already multiple ways to do it, but I added it anyway, for convenience and parity with UE. Category is "Primitive"

![image](https://user-images.githubusercontent.com/7001068/196428026-1a9187a5-6a53-4bd5-a6e6-0c5e6175b64e.png)

Basically replicates either of the following:

![image](https://user-images.githubusercontent.com/7001068/196428243-df690963-cbe8-4f05-b43d-4c1df60cdb8b.png)

![image](https://user-images.githubusercontent.com/7001068/196428291-4e150694-92b5-4b83-9b4b-79aa5ea305e1.png)

Also fixed "Face" node, which was incorrectly stating that value was +1 for front, and -1 for back, when it was actually +1 for front and 0 for back.

**Comment by Dawie3565** [comment]
Thank you 
Note switch by face node (Before) with Oculus Quest failed to build an produce errors 
the TwoSidedSign worked an also worked in URP OpenGL 

see 
https://discordapp.com/channels/461534117297913866/1030851287933259796
